nnstreamer/TAOS-CI

README.md
---
```bash
- Bullet points are okay, too
- Typically a hyphen or asterisk is …
```
=> Replaced gitjub.sec.samsung.net with github.com

README.md
This commit is trivial. It is to update the existing introduction.
---
```bash
Further paragraphs come after …
```
=> Updated introduction of manual - @open sesame 08/12 13:59

ci/standalone/plugins-base/pr-audit-build-yocto.sh
This commit is to enable Yocto/Poky(X86 i586) based on Extensible
Software Development Kit (eSDK).
* eSDK for Yocto/Poky:
* https://wiki.yoctoproject.org/wiki/Application_Development_with_Extensible_SDK
* Note that currently the Yocto Project autobuilder only builds "full" eSDKs.
* https://downloads.yoctoproject.org/tools/support/workflow/poky-glibc-x86_64-core-image-minimal-i586-toolchain-ext-2.2.sh
1. Updated annotations
2. Enabled eSDK for Yocto/Poky(X86 i586)
3. Added debug messages
1. locat test: okay
2. gbs build: okay
---
Please remove unused part of the template after writing your own PR …
=> Activitated Yocto/Poky(i586) based eSDK - @open sesame 08/16 19:24

ci/standalone/ci-server/install-packages.sh
This commit is to hel administrator that has to maintain
his own CI server directly.
1. Added script to install prequisites in ci server
1. locat test: okay
---
```bash
blank line separating the summary from the …
```
=> Added script to install dependant packages in ci server - @open sesame 08/16 19:25

ci/standalone/ci-server/README.md
This commit is to update the out-of-date documents that is required to
set-up CI server.
1. Added Ubuntu and Yocto pre-requisites
2. Updated configuration files for platform build
3. Updated the out-of-date instruction manuals
4. Added a install script to prepare required pakcages
---
```bash …
```
=> [Documentation] Updated document of CI server - @open sesame 08/17 10:41

README.md
This commit is to update the existing introduction of TAOS-CI for opensource project.
1. Added a goal of TAOS-CI
2. Updated the statements (e.g., introduction, goal)
3. Removed an unnecessary explanation
---
```bash
blank line …
```
=> Documentation: updated introduction of TAOS-CI for opensource project

README.md
This commit is to add a reference section in README file.
1. Added a reference section
---
```bash
various tools like `log`, `shortlog` and `rebase` can get confused …
```
=> Added reference section in README.md

README.md, ci/standalone/checker-pr-format-async.sh
It is tirivial. This commit is to update a content of document
---
```bash
Further paragraphs come after …
```
=> Doc: updated content of document - @open sesame 08/23 20:13

ci/doc/how-to-install-taos-ci.md
This commit is to update how to set-up CI server and CI software.
---
```bash
Further paragraphs come …
```
=> Updated How to set-up CI server

README.md
This commit is trivial. It is to update the existing contents of TAOS-CI document.
---
```bash
Further …
```
=> doc: updated taos-ci manual

README.md
This commit is trivial. It is to add modulable facilities that we provide via
plug-in interface (e.g., base, good, and staging.)
---
```bash
various tools like `log`, `shortlog` and `rebase` can get …
```
=> Doc: Added current modulable facilities

ci/standalone/ci-server/README.md
Can't create multiple doxygen files at same times.
So add note about that.
=> [Doxygen] Add precautions about crontab.

ci/doc/how-to-install-taos-ci.md
This commit is to update the existing TAOS-CI installation manual to help users that do not have CI experience enough.
1. Updated installation manual of TAOS-CI for user convenience
2. Removed unnecessary explanations
---
```bash
subject of the commit and the rest of the text as the body. …
```
=> Doc: updated TAOS-CI installation manual

README.md
It is trivial. This commit is to resize the height of architecture picture for readability.
---
```bash
if you run the two …
```
=> Resize height of architecure image

ci/taos/config/config-environment.sh
This commit is to remove unnecessary variable $EMAIL in config file.
---
```bash …
```
=> [config] Removed unnecessary variable

ci/taos/webhook.php
It's trivial. This commit is to update annotations of webhook hander (php).
---
```bash …
```
=> Updated annotations of webhook hander (php)

ci/taos/checker-pr-audit-async.sh, ci/taos/config/config-plugins-audit.sh
Change organization to set up new plugins easily.
=> [audit] Change audit plugins organization.

ci/doc/how-to-setup-taos-ci-server.md
It is trivial. This commit is to fix the existing incorrect link (webapp folder).
---
```bash
Further …
```
=> Fixed incorrect link (webapp folder)

ci/taos/checker-pr-format-async.sh, ci/taos/config/config-plugins-format.sh
Change organization to set up new plugins easily.
=> [format] Change formant plugins organization

README.md
It's trivial. However, it is important for TAOS-CI users.
This commit is to update the module list and future work.
---
```bash
if …
```
=> doc: updated module list

ci/taos/config/config-plugins-format.sh
=> [typo] fix typo

ci/taos/plugins-base/pr-audit-build-yocto.sh
Note that administrator of a server has to specify the location of eSDK at first".
And then, user has to change the BUILD_MODE from 99 to 0.
1) Yocto: BUILD_MODE = 99 (skip, by default)
Skipping 'devtool' procedure temporarily because BUILD_MODE is 99.
'777' will be used for a fine-graind classification when the values of 'build_result' are increased.
$build_result=777
2) eSDK:  $YOCTO_ESDK_ROOT == ""  (Administrator has to install eSDK/Yocto)
Skipping 'devtool' procedure temporarily because YOCTO_ESDK_ROOT is empty."
In this case, ask administrator of a server to install Yocto eSDK.
'888' will be used for a fine-graind classification when the values of 'build_result' are increased.
$build_result=888
---
In general, github system …
=> Yocto: Exception handling in case that Yocto eSDK is not installed

ci/doc/how-to-setup-taos-ci-server.md
* Resolve: issue #211.
If you want to use your own domain name address instead of IP address,
we recommend that you try to get a host name free of charge at https://freedns.afraid.org.
```bash
$ sudo vi /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:80>
ServerName {your_host}.mooo.com
ServerAdmin webmaster@localhost
DocumentRoot /home/taos-ci/public_html
ErrorLog ${APACHE_LOG_DIR}/error.{your_github_repo_name}.log
CustomLog ${APACHE_LOG_DIR}/access.{your_github_repo_name}.log combined
</VirtualHost>
$ sudo systemctl restart apache2
```
--- …
=> doc: Added how to setup domain name address

ci/doc/maintenance.md
This commit is to replace email address with github.com address
in order to use community information instead of company email address.
1. Replaced company information with community account
---
```bash
blank line separating …
```
=> doc: updated email address of contributors

ci/doc/how-to-install-taos-ci.md, ci/taos/checker-pr-audit-async.sh, ci/taos/config/config-server-administrator.sh, ci/taos/plugins-base/pr-audit-build-yocto.sh
This commit is to append a configuration file for a server administrator. The server
administrator has to install required packages and development environment for CI
server. As we all know, an initial setting is not done by administrator.
So, let's support a configirstion file for the server administrator.
* file: ./config/config-server-administrator.sh
---
```bash
characters or so. In …
```
=> config: Added configuration file for server administrator

packaging/.gbs.conf
This commit is to update a configuraiton file of gbs
for Tizen software platform.
---
```bash
Further …
```
=> Updated configuraiton file of gbs for Tizen

ci/doc/how-to-setup-taos-ci-server.md, ci/taos/webapp/install-packages.sh
This commmit is to update the existing document and apt list
for set-up procedure of server administrator.
---
```bash
if you run the two …
```
=> server: updated document and apt list for server set-up

ci/gcov/coverage-generator.sh
add sudo to remove folder and clean tag.
2. Run test: [* ]Passed [ ]Failed []Skipped
=> [unittest] Fix coverage generator error

ci/doc/how-to-install-taos-ci.md
It is trivial. This commit is to fix typos in installation document.
---
```bash …
```
=> doc: Fixed typos in installation document.

ci/gcov/coverage-generator.sh
Add sudo command to remove password request
and fix error and typo
=> [coverage] Remove password request

ci/taos/webapp/install-nnstreamer-packages.sh, ci/taos/webapp/install-packages.sh
To run nnstreamer sample apps, need some packages.
For installing packages easily, make script that installs packages automatically.
2. Run test: [ *]Passed [ ]Failed []Skipped
=>  [packages] Make install packages script - @open sesame 09/11 07:34

README.md, ci/doc/how-to-setup-taos-ci-server.md, ci/doc/self-assessment-before-submitting-pr.md
This commit is to append how to do a self assessment for Ubuntu packaging work.
Note that contributors have to execute a self assessment before submitting your PR.
We describe how to verify if your commit(s) is valid. To complete a source code verification,
we strongly recommend that contributors execute a clean build with a latest version of
a software platform. A partial validation inspection of software cause potential defects
when the software is integrated into the software platform.
* For APT repository of Tensorflow and NNstreamer
deb [trusted=yes] http://ppa.launchpad.net/nnstreamer/ppa/ubuntu xenial main
1. Updated how to setup TAOS-CI server
2. Updated self assessment manaul
3. Updated guide documents
Signed-off-by: Geunsik Lim …
=> doc: update apt repository of Ubuntu distro

ci/taos/webapp/monitor.php
It is trivial. This commit is to update the existing terminology of web application
correctly after implementing three queues (e.g., wait, ready, and run queue).
1. Updated a description for webapp monitoring
---
```bash
blank …
```
=> webapp: Updated description to view PR status

README.md
This commit is to memorize acceptance of our technical paper that was submitted
to IEEE ICCE conference committee. The paper will be appeared a IEEE digital library
in January next year.
1. Added a paper acceptance
---
```bash …
```
=> doc: Added ICCE 2019 technical paper (accepted)

ci/taos/plugins-good/pr-format-indent.sh
Change the link properly.
fix : https://github.com/nnsuite/nnstreamer/issues/541
=> [Fix] Change pr-format-indent detail link properly

ci/taos/config/config-plugins-audit.sh, ci/taos/plugins-staging/pr-nnstreamer-ubuntu-apptest.sh
'pr-nnstreamer-apptest' should be improved more. This is initial commit.
**Changes prposed in this PR:**
- config-plugins-audit.sh: Add pr-nnstreamer-apptest plugin
- pr-nnstreamer-apptest.sh: Write initial code.
* Reference: https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots
2. Run test: [ *]Passed [ ]Failed []Skipped
=> [nnstreamer] added apptest module to verify example applications

ci/gcov/coverage-generator.sh
It is trivial. Fix checking directory logic
---
```bash
**Changes …
```
=> [Fix] fix typo

ci/doc/how-to-setup-taos-ci-server.md
It is trivial. This commit is to update the existing document for setting-up a CI server.
---
```bash …
```
=> doc: update ci server manual

ci/doc/how-to-install-taos-ci.md
This commit is to update an existing instruction manual to help a server administrator 
that has to set-up a development environment to run TAOS-CI system.
---
```bash
various tools like `log`, …
```
=> doc: improve a setting guide of CI server

ci/taos/plugins-staging/pr-nnstreamer-ubuntu-apptest.sh
=> [nnstreamer/apptest] Add log about apptest

ci/taos/webhook.php
It is trivial. just add ')'
---
```bash
**Changes proposed in …
```
=> [typo] missng ')'

ci/taos/plugins-good/pr-format-doxygen-tag.sh
**Changelog:**
Version 2:
- Add skip status for none source code commit.
Version 1:
- 'success' value is default. so set value to 'success' is not necessary.
=> [Fix/doxygen-tag] Fix overwriting result bug

ci/taos/webhook.php
Note that the 'substr_replace' function doe not generate a same result
among the PHP versions when a string includes special characters.
This commit is to prevent an unexpected error of webhook handler due to a string,
includes special characters such as space, reverse slash, and doller symbol.
It will be automatically replaced a defiended special character with "_" character.
From our experiment, we may handle just "space" character. If you meet another special
character, please append the special character into $vowels array variable.
* Error code:
PHP Catchable fatal error: Object of class stdClass could not be converted to string in ...
---
Please …
=> [Urgent] webhook handler: improve str_replace() to hide secret value

ci/taos/plugins-staging/pr-nnstreamer-ubuntu-apptest.sh
1. Applying virtual display, device, and video frames for test.
=> [apptest] Applying fake usb camera for apptest

ci/taos/plugins-good/pr-format-sloccount.sh, ci/taos/webapp/install-packages.sh
This commit is to append languages such as .sh and .php.
When a commit includes a file format of specified languages
among the source code files.
1. Added source code formats
2. Added --datadir option
=> slocc: add .sh and .php to append a source range

ci/doc/how-to-use-taos-ci-module.md
This commit is to guide a requirement before submitting a pull request
in order to merge new CI module to TAOS-CI repository.
1. Added a guide document to help how to merge new CI module.
---
```bash
blank line separating the …
```
=> Doc: Requirement for merging new CI module

ci/taos/plugins-staging/pr-nnstreamer-ubuntu-apptest.sh
1. Using 'insmod' instead of 'modprobe'
2. Handling exception case that uninstalled v4l2loopback.
=> [nnstreamer/apptest] Applying 'insmod' instead of 'modprobe'

ci/taos/config/config-plugins-audit.sh, ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to rename the existing module name for nnstreamer apptest.
* before:pr-{module-name}.sh
* after :pr-{type}-{module-name}.sh
* Guide:
First of all, **Note** that you have to run the below statement in order to check the grammar error of a CI module that your write.
```bash
$ bash ./pr-{type}-{module-name}.sh
```
When you submit a pull request to merge your CI module to TAOS-CI repository, Please note that reviewers check 4 requirements
as follows before merging your pull request.
* Maintenance: The module has to be normally executed as a CI component after enabling the module via a configuration file.
* Readability: Most of the developer should be able to read source code of the CI module without difficulty.
* Execution time: The time required to execute the module should …
=> NNStreamer module: rename a module of apptest

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
1. Edit wrong path of log files for checking where the error comes.
2. Change Xnvc port to 11 from 0
3. Fix typo.
=> [nnstreamer/apptest] Fix apptest bug

ci/taos/webapp/install-nnstreamer-packages.sh
- Add python gstreamer packages for nnstreamer apptest.
---
```bash
Further paragraphs come after blank …
```
=> [package] Add python packages for nnstreamer apptest

ci/taos/config/config-plugins-format.sh
It is trivial. Remove duplicated messages in 'config-plugins-format.sh'
---
```bash
Further paragraphs come …
```
=> [Fix] Remove duplicated log messages.

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
It is trivial. change report name 'pr-nnstreamer-apptest'-> 'pr-audit-nnstreamer-apptest'
---
```bash …
```
=> [Fix] change test module name

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
Append log to appropriate log file via result
fixed issue: https://github.com/nnsuite/nnstreamer/issues/685
=> [Fix] Fix abnormal of apptest log

ci/doc/contributing.md
---
```bash
- Bullet points are okay, too
- Typically a hyphen or asterisk is …
```
=> add period

ci/doc/coding-convention.md
---
```bash
- Bullet points are okay, too
- Typically a hyphen or asterisk is …
```
=> add period in sentence.

ci/taos/plugins-base/pr-audit-build-tizen.sh
Add debug message to measure time of gbs build.
=> [gbs] Measure gbs build time.

debian/changelog
This commit is to update the existing changelog file to archive
history of the version release.
---
```bash
if you run the two …
```
=> debian: update changelog file

ci/doc/how-to-install-taos-ci.md, ci/jenkins/README.md
This commit is to move the existing jenkins howto to ./jenkin folder.
We need to move the jenkins content to avoid unnecessary reading of TAOS-CI users.
1. Added README.md in jenkins folder
2. Removed (optional) jenkins guide in TAOS-CI setting guide
---
```bash
subject of the commit and …
```
=> doc: Created README.md in ./jenkins folder

ci/taos/plugins-good/pr-format-indent.sh
It is trivial. check indent package
---
```bash
**Changes …
```
=> [package] Add missing package

ci/taos/plugins-base/pr-audit-build-tizen.sh, ci/taos/plugins-base/pr-audit-build-ubuntu.sh
result value get return of date. so fix that.
---
```bash …
```
=> [Fix] fix getting date result.

README.md
This commit is to append reference papers in the README.md file.
Three papers are referenced to design and implement TAOS-CI.
1. Added proposed in this PR:**
---
```bash …
```
=> doc: Added reference papers in READMD.md

ci/doc/how-to-setup-taos-ci-server.md
change user from root to www-data cause of /var/cache/pbuilder authority.
---
```bash …
```
=> [doc] edit description of crontab.

ci/taos/webapp/monitor.php
Fixed issue https://github.com/nnsuite/nnstreamer/issues/789
This commit is to fix the bug of PR monitor.
1. fixed bug of PR monitor
---
=> [Urgent] web: Fixed a bug of state transition monitor for PR

ci/taos/checker-pr-audit-async.sh
This commit is to update the existing PR scheduler to improve
readability and portability.
* Version 2:
1. Removed duplicated statements.
2. Added debug message for a server administrator
3. Changed waiting time to avoid unexpected entrance into a run queue
* Version 1:
1. Updated statement to compare current queues and maximum queues.
=> scheduler: updated PR scheduler for readability and portability

ci/taos/checker-pr-audit-async.sh
This commit is to append a run-queue controller to manage a execution management of Ubuntu build tasks. 
**Changes proposed in this PR:** 
1. Added run-queue controller for Ubuntu (pdebuild) 
2. Calculated of running jobs both Tizen and Ubuntu 
=> Scheduler: Added Run-queue controller for Ubuntu build

ci/taos/menu.html, ci/taos/webapp/pstree.php
This commit is to replace htop with pstree in order to
dislay a tree of processes when a PR hang issue happens.
1. Added pstree.php
2. Removed htop.php
---
=> Webapp: Replace htop with pstree to show a process tree

ci/gcov/coverage-generator.sh
For unit test coverage, unit test is required. so add flag.
---
```bash
Further paragraphs come after blank …
```
=> [Coverage] Add unit_test flag in gbs build

ci/taos/checker-pr-audit-async.sh, ci/taos/checker-pr-format-async.sh, ci/taos/checker-pr-gateway.sh
swap 'input_pr' and 'input_date'. It makes easily find repo folder and change path. in example, type {pr-number} and push tab.
Fixed issue #410.
---
=> [CI] change 'dir-commit' variable.

ci/taos/config/config-environment.sh
Until now, a lot of function have been modified to improve the issues of
the existing components. Based on the latest components, this commit is to
update the existing config-environment.sh file for maintenance.
1. Updated version number
2. Update annotations of variables
3. Added additional comments for CI administrator
---
=> Config: Update config-environment.sh file

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This patch is trivial, removing unnecessary whitespaces in the script file.
=> [nnstreamer/apptest] Remove unnecessary whitespaces

ci/taos/checker-pr-audit-async.sh, ci/taos/common/global-variable.sh, ci/taos/plugins-base/pr-audit-build-tizen.sh, ci/taos/plugins-base/pr-audit-build-ubuntu.sh
This commit is to improve the operation to archive binary package files.
1. Updated annotation
2. Removed duplicated copy operations
3. Moved 'move' operation to each build module for consistency and maintenace
4. Improved the complicated folder structure to archive package files
5. Fixed typos
5. Added a common file to maintain global variable consistently
Signed-off-by: www-data <www-data@ip-172-31-27-164.ap-northeast-2.compute.internal>
---
=> [Build] Improve operation to archive packages

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to fix incorrect port number of Xvnc.
The VNC server listens on three ports: 5800 (for VNC web), 5900 (for VNC),
and 6000 (for Xvnc). Run a Xvnc service with a port number 6011 in order
to avoid a conflict possibility with existing Xvnc service ports(6000 ~ 6010),
1. Fixed incorrect annotation of Xvnc
2. Added display message with netstat command
3. Updated some comments
---
=> nnstreamer/apptest: Fixed incorrect port info of Xvnc

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
Fixed issue:
* https://github.com/nnsuite/nnstreamer/issues/905
* https://github.com/nnsuite/nnstreamer/issues/924
This commit is to change the default test application to do a run test.
Note that (1)/dev/video & ()VNC based GUI applications are still unstable. So,
we need to to run nnstreamer_sink_example application only until we completely
fix the these applications.
1. Run application test (=consumer) when producer is normally launched.
2. Enabled just nnstreamer_sink_example applicaiton
3. Updated annotations for readability
---
=> nnstreamer/apptest: Enable nnstreamer_sink_example application just

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to fix the existing incorrect statement to handle
/dev/video? (fake camera).
1. Fixed a if statement to handle correctly /dev/video?
2. Updated the existing producer and consumer routine.
---
=> nnstreamer/apptest: Fixed incorrent handling of /dev/video file

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
* Related issue: https://github.com/nnsuite/nnstreamer/issues/905
This commit is to add other test applications again because
we have completed the aging test enough.
1. Added other test applications.
2. Updated annotations.
---
=> nnstreamer/apptest: Enable other applications

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
It is trivial. This commit is to fix a typo and incorrect location
of debug message (e.g., env command)
1. Moved the location of function for readability and consistency
2. Fixed typo
3. Moved the location of 'env' debug message
---
=> nnstreamer/apptest: Fixed typo and incorrect location of debug message

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to rename the existing Xvnc variables for readability and
maintenance.
1. Renamed the existing Xvnc varaibles
(e.g., Xvnc PID and the default port of Xvnc)
Signed-off-by: leemgs <leemgs@gmail.com>
---
```bash
blank line separating the summary from the body is …
```
=> nnstreamer/apptest: Renamed Xvnc variables for maintenance

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to update the exsiting comments for readability and
maintenance of an apptest module.
**Changes**
* Fixed typos
* Appended addition annotations for maintenance
---
=> apptest: Updated the existing annotations for maintenance

README.md
This commit is to update the content of ICCE paper that is presented
on Jan-12-2019 at LasVegas, NV.
---
=> doc: updated the status of ICCE paper

ci/taos/test/pr-report.sh
This commit is to update the existing 'pr-report.sh' file.
In order that an administrator test and manage the webhook APIs,
the group inspectors are generally passed by administrator.
**Changes**
1. Updated annotation.
2. Added (info)***.
3. Replaced three examples with one example.
---
=> admin: update the webhoo api script for maintenance

ci/taos/config/config-environment.sh
This commit is to update the existing version information of TAOS-CI
to maintain the features among the different versions.
---
=> Maintenance: update latest version number

ci/taos/checker-issue-comment.sh
It's trivial. This commmit is to update the existing annotation to improve
a readability and maintenance of the issue check module.
---
=> Maintenance: Update the existing comment of an issue checker

ci/taos/plugins-base/pr-audit-build-android.sh
This commit is to interconnect the android build module and the Apache
webserver ID in order to compile nnstreamer C/C++ source code to support
Android platform (e.g., 7.0/Nougat).
**Changelog**
* Version 2:
1. Updated the variable 'result' to accumulate the execution result.
2. Fixed incorrect folder path to save log filess for debugging.
3. Updated annotations
* Version 1:
1. Stablized the statement after completing the aging test enough in real server.
2. Removed unnecessary statements for readability and code maintenance
3. Executed export statements instead of using ~/.bashrc of www-data for portability.
---
=> [URGENT] Android/ARM64: interconnect android build module and apache web

ci/jenkins/taos-platform-free-space.sh, ci/taos/checker-pr-audit-async.sh, ci/taos/plugins-good/pr-format-executable.sh
It's trivial. This commit is to fix typos.
---
=> Maintenance: fixed typos

ci/taos/plugins-good/pr-format-pylint.sh
This PR fixes several bugs related to https://github.com/nnsuite/TAOS-CI/issues/476
Note that run-test was done in the local environment only.
Resolves #476 
=> [Module/PR/Python] Fix bugs in the pr-format-pylint script

ci/taos/plugins-base/pr-audit-build-ubuntu.sh
This commit is trivial. It is to update the existing
echo statement consistently.
Siened-off-by: junghan <junghan@skku.edu>
---
=> Build: update echo statement in ubuntu builder

ci/taos/test/pr-comment.sh, ci/taos/test/pr-report.sh
This patch is trivial. It is to fix incorrect
statements in test modules.
Signed-off-by: junghan <junghan@skku.edu>
---
=> Test module: Fix typo and annotation

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is trivial. It is to update the existing out-of-date statements
to improve the readability and keep the maintenance.
---
=> [module] nnstreamer: Updated the existing annotations in apptest module

ci/taos/checker-pr-gateway.sh
Fixed issue #483.
This commit is to improve the exsiting PR gateway that distributes tasks..
When a webhook handler receive the event messages from the PRs,
The webhook handler call the PR gateway. Then, the PR gateway runs
the format (prog1) and audit (prog2) group in parallel.
Prog1 and Prog2 woudl be started in the background.
---
=> PR gateway: Run the format (prog1) and audit (prog2) group in parallel.

ci/taos/config/config-environment.sh
This commit is to improve the existing comments in the configuration file
to hlep developers that want to install TAOS-CI in their own server.
This commit is written to apply commentat that is reported by Wook Song.
---
=> [Maintenance] Config: update the comments of configuration file

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to display a time cost that is required to build and run
test applications.
---
=> apptest: Added a time check

ci/taos/checker-pr-audit-async.sh, ci/taos/checker-pr-format-async.sh, ci/taos/checker-pr-gateway.sh, ci/taos/config/config-environment.sh
Working on issue #485
This commit introduces dependency between the various groups.
If the dependency is set, failure of one group will cause other groups to skip
If the dependency is not set, all the groups will run in parallel
Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>
=> PR gateway: Added dependency between the groups to run in parallel/sequence

ci/taos/checker-pr-audit-async.sh, ci/taos/checker-pr-format-async.sh, ci/taos/checker-pr-gateway.sh, ci/taos/config/config-environment.sh
=> Revert "PR gateway: Added dependency between the groups to run in parallel/sequence"

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
Fixed issue https://github.com/nnsuite/nnstreamer/issues/1265.
The existing apptest module always download the same files such as
a network model and label file repeatedly. This commit is to improve
the existing operation to reduce a waiting time and save a network
cost of AWS instance.
---
=> apptest: improve routine that download tflite files @open sesame 03/27 17:58

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to fix incorrect statement.
---
```bash …
```
=> apptest: fixed typo

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to fix incorrect indentation and Doxygen grammar.
**Changelog**
1. Fixed indentation
2. Updated Doxygen grammar
- from # to ## to probe an annotation of functions
---
=> apptest: fixed incorrect indentation and doxygen statement

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is trivial. It is to update the existing statement in
the nnstreamer application test module.
---
=> apptest: Fix typos

README.md
This commit is add to the paper publication activity such as KCC conference
The conference is one of the major domestic conferences in south Korea.
---
=> doc: Added paper publication (domestic conference)

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to append "--header" option to wget statement to set up
a character set.
(e.g.,  --header="Accept-Charset: utf-8" --header="Accept-Language: en")
**Changes**
1. Added --header option for setting up a charset
2. Replaced .log with .txt
---
=> apptest: Added --header in wget command

ci/taos/checker-pr-audit-async.sh
This commit is to improve a readability and maintenance of the
existing audit module. The existing annotations will be update
appropriately after this PR.
---
=> doc: updated the annotations of the audit module

ci/taos/plugins-base/pr-audit-build-tizen.sh
This commit is trivial. This commit is to update the existing comments
in the Tizen build module.
---
=> doc: update comment of tizen build module

ci/taos/common/out-of-pr-killer.sh
This commit is trivial. It is to update the existing comment of OOP killer
for maintenance and readability.
---
=> doc: updated the comment of OOP killer

ci/taos/webapp/monitor.php
This commit is to append variables for monitoring a Yocto build status.
**Changes**
1. Added variables for Yocto
2. Changed a display size of sleep image (from 100 to 50)
---
=> webapp: Declared variables for Yocto monitor

ci/taos/plugins-good/pr-format-newline.sh
Fixed issue #520.
This commit is to fix an incorrect execution of the newline checker when
the file type of .md file is "UTF-8 Unicode text".
---
=> Fixed a bug of the newline checker

ci/taos/webapp/install-packages-nnstreamer.sh
This commit appends pytorch to installed packages to build nnstreamer for apptest
Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>
=> [nnstreamer/apptest] Added dependency: pytorch

ci/taos/config/.htaccess
This commit is to append '.htaccess' file by default to strengthen
the guard at the entrance such as configuration files. It is to help
a newbie that do not have a security knowledge.
**Changelog**
- Added .htaccess file by default
- Do not provide .htpasswd file by default
=> security: apply more strict security for config file

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
Since it is based on tflite, the name `tflite` is appended
Signed-off-by: Hyoung Joo Ahn <hello.ahn@samsung.com>
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped
=> [AppTest] change the name of image classification

ci/taos/common/api_collection.sh
Fix typo and remove unnecessary space in script.
=> [Typo] typo correction

ci/taos/plugins-base/pr-audit-build-android.sh
Add script to build Android API library.
To build NNStreamer Android API, pre-built libraries (gstreamer and tf-lite) and gradle build-scripts are needed.
When building the API library, pre-downloaded files are copied into build directory and run gradle-build.
**Changelogs**
* Version 4:
- update prerequisites and dependency with review comment
* Version 3:
- limit api module to build android library
* Version 2:
- remove sudo in the script
* Version 1:
- initial commit to add script for android api
=> [Android] Add script to build Android API

ci/taos/plugins-base/pr-audit-build-android.sh, ci/taos/plugins-base/pr-audit-build-tizen.sh, ci/taos/plugins-base/pr-audit-build-ubuntu.sh, ci/taos/plugins-base/pr-audit-build-yocto.sh, ci/taos/plugins-good/pr-format-clang.sh, ci/taos/plugins-good/pr-format-indent.sh, ci/taos/plugins-good/pr-format-newline.sh, ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
1. Fix indentation in scripts and remove white space.
2. Remove '$' on the left side of assignment.
=> [Script] fix indent and value assignment 

README.md
This commit is to update the current status of the paper
that is submitted to KCC conference. The paper is finally published.
---
=> doc: Updated paper status for KCC

ci/taos/plugins-base/pr-audit-build-android.sh
Added calling the script to modify the header when building for non-tizen build, tizen in this case
Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>
=> [android] Added modifying header for android

README.md
This commit is trivial. It is to update the work status of the papers.
---
=> doc: Updated README.md for papers

ci/taos/config/config-plugins-format.sh, ci/taos/plugins-good/pr-format-shellcheck.sh
Fixed issue https://github.com/nnsuite/TAOS-CI/issues/527.
This commit is to append a new module to investigate if the shell script
files include syntax errors.
**Changelog**
* Added shell check module newly.
* Added configuration variable for shellcheck module.
---
=> module: added new module to check syntax errors in shell script

ci/doc/how-to-use-taos-ci-module.md
This commit is to update the existing manual that explains how users
can develop their new module newly.
**Changelog**
* Fixed typos.
* Added '-n' option to check syntax errors of the new module.
---
=> doc: Updated the manual to develop new module

ci/doc/how-to-use-taos-ci-module.md, ci/taos/webapp/install-packages-base.sh
This commit is to update the existing install-package-base.sh
to set-up the shell syntax checker.
**Changelog**
* Updated the install-package-base.sh
* Updated the how to use taos-ci module manual.
---
=> package: updated install-packages-base.sh for shell syntax checker

ci/doc/how-to-use-taos-ci-module.md
This commit is trivial. It is to append how to write wiki page for
new module.
---
=> doc: Added how to write wiki page for new module

ci/doc/how-to-use-lcov-to-generate-code-coverage-stat.md
This commit is trivial. It is to update how to generate the existing code
coverage manual.
---
=> doc: updated how to generate the code coverage with gcov/lcov

ci/doc/how-to-use-taos-ci-module.md, ci/gcov/coverage-generator.sh, ci/taos/checker-pr-audit-async.sh, ci/taos/checker-pr-format-async.sh, ci/taos/checker-pr-gateway.sh, ci/taos/common/api_collection.sh, ci/taos/common/out-of-pr-killer.sh, ci/taos/plugins-base/pr-audit-build-android.sh, ci/taos/plugins-base/pr-audit-build-tizen.sh, ci/taos/plugins-base/pr-audit-build-ubuntu.sh, ci/taos/plugins-base/pr-audit-build-yocto.sh, ci/taos/plugins-good/pr-format-cppcheck.sh, ci/taos/plugins-good/pr-format-doxygen-build.sh, ci/taos/plugins-good/pr-format-flawfinder.sh, ci/taos/plugins-good/pr-format-indent.sh, ci/taos/plugins-good/pr-format-misspelling.sh, ci/taos/plugins-good/pr-format-prohibited-words.sh, ci/taos/plugins-good/pr-format-shellcheck.sh, ci/taos/plugins-good/pr-format-sloccount.sh, ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh
This commit is to replace "check_dependency" with "chk_cmd_dep" to
improve the readability of source code.
---
=> Replace check_dependency with chk_cmd_dep

ci/taos/plugins-base/pr-audit-build-android.sh
Use patch file to apply the patch
Cleanup the patch applied (for non-tizen cases) after build completes
Ubuntu build cleanup is handled in ubuntu build script
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped
Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>
=> [android] Cleanup after testing

ci/taos/plugins-base/pr-audit-build-android.sh
Add steps to modify the gstreamer-1.0.mk for ndk build.
=> [Android] update prerequisites to build API

ci/doc/how-to-build-gbs-pdebuild.md
This commit is trivial. It is to update the document.
---
=> doc: Updated the gbs build document

ci/taos/common/api_collection.sh
This commit is to fix a security hole while displaying helpful debug messages.
---
=> security: fixed a security hole

ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to change the commit task after checking
the execution result of the cov-build command.
---
=> Coverity module: Fixed commit routine after cov-build

ci/cron/coverity-github.sh, ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to display additional contents after executing
the coverity scan (e.g., scan.coverity.com)
**After this PR:**
Defect summary:
- Last Analyzed: Nov 01, 2019
- Lines of Code Analyzed: 298,960
- Defect Density 0.11
Total defects: 70
- Outstanding: 34
- Dismissed:
- Fixed: 21
Defect changes:
- Newly detected: 0
- Eliminated: 0
And then, the above data will be utilized to control the cibot status and the cibot comment.
---
=> coverity module: Added report data of analysis metrics

ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to display the coverity report into the comment window of a PR.
---
=> coverity module: Added comment message format

ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to improve the exsitng code routines of the coverity module.
**Changelog**
* Added a comment style with the mark down format.
* Added coverity Scan summary.
* Added defect icons to give a PR submitter a warning information
* Added yellowcard and redcard status.
---
=> module: Refactorred the functions of coverity module

ci/taos/config/config-environment.sh
This commit is to append a variable in the configuration file to control
the threshold of the warning zone (e.g., yellow card).
---
=> config: Updated configuration file for coverity

README.md
This commit is to append badges to show the current project status.
Right. It is to give users readability and understanding of this project.
---
=> Added badges to show the current project status

ci/badge/gen_badge.py, ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to append a json-format file to support
the coverity badge with shields.io service.
The entire operation sequence is as follows:
TAOS-CI --> coverity module --> create badge_coverity.json -->
display with the badge image service of shield.io
**Changelog**
* Added a rountime to generate badge_coverity.json
* Added comment to describe how to use gen_bade.py (for unittest)
---
=> badge:Added coverity badge file with jason

ci/cron/coverity-github.sh
This commit is to improve the functions of the existing
coverity script file for readability, compatibility, and
maintenance.
---
=> Updated crond-based coverity script

ci/taos/plugins-good/pr-prebuild-coverity.sh
This PR is trivial.  This commit is to fix incorrect variable name.
---
=> coverity: fixed the typo

ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to remove the existing hard-coded variables to
improved reusability and portability.
---
=> coverity module: Removed hardcoded variables

ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to improve the execution time of the coverity scan
when  the current time is not appropriate time to build and commit the
nnstreamer source codes to the Coverity Scan Cloud (e.g., https://scan.coverity.com)
Currently, the default execution frequency is 12 hours for nnstreamer repository.
As a basic policy. We do not use cron daemon to run the build & commit task.
The execution time is dependent on the PR frequency that is submitted by contributor.
**Changelog**
* Fixed typos
* Enabled on/off step of the build/commit tasks
* Added debug message for maintenance
---
=> coverity module: improved performance of the coverity scan

ci/taos/plugins-good/pr-prebuild-coverity.sh
coverity: Enabled yellow card & red card policy
This commit is to start the fine-grained coverity management with
a yellow and red card policy for GitHub repository.
**Changelog**
* Added yellow card and red card instead of warning card
* Enabled failure policy in case that the outstanding defects
exceed the number of redcards
* Removed a warning card routine
=> Upstream coverity cards

ci/badge/README.md
This commit is to append README.md to support badges
for GitHub repositories.
---
=> badge: Added README.md

ci/taos/plugins-good/pr-prebuild-coverity.sh
This commit is to append improve the readability of the existing
coverity module.
**Changelog**
* Replaced $i with $file for readability
* Removed unnecessary data (e.g., stat_total_defects)
* Changed the criteria from #-of-defects fto #-of-ounstanding-defects
* Updated the debug messages
* Updated the report styles with yellow card, red card, and critical card
---
=> Refactoring: Improved coverity module

ci/taos/checker-pr-comment.sh, ci/taos/config/config-environment.sh
This commit is trivial. It is to change the version name and display method.
---
=> Updated version name of TAOS-CI

ci/taos/checker-pr-comment.sh
This commit is to append 1commit/1PR policy whenever
a PR is submitted.
---
=> Added 1commit/1PR policy

ci/taos/common/global-variable.sh
This commit is to colorize a terminal and shell environemtn to
improve readability of the display message.
---
=> Added array var to support colorizing terminal

ci/taos/webapp/pr-handler.php
Fixed issue #608
This commit is to fixe the issue #608.
---
=> WEB: Updated the PR Handler

ci/taos/config/config-environment.sh
This commit is to announce the version 1.5.2020324
with additional minor fixes since we have verify the stability
of the TAOS-CI for 6 months (Sep-2019 to Mar-2020).
* https://github.com/nnsuite/TAOS-CI/releases/tag/v1.5.20200324
---
=> Release: version 1.5.20200324

ci/taos/webapp/pr-handler-proceed.php
Condition and echo message are contradictory.
**Changelog**
* Fixed typo
* Removed debug message
Signed-off-by: gichan-jang <gichan2.jang@samsung.com>
=> Web : Edit comments on PR handler

ci/doc/how-to-install-taos-ci.md, ci/doc/how-to-setup-taos-ci-server.md
This commit is to update the existing documents to improve
a readability and to help TAOS-CI users.
---
=> doc: Updated the existing manual documents @open sesame 03/25 10:16

ci/doc/how-to-setup-taos-ci-server.md
This commit is trivial. It is update the existing documents
in order that users can more easily set-up the TAOS-CI system
for their projects.
---
=> doc: Updated the document for users - @open sesame 03/25 15:07

ci/taos/plugins-good/pr-prebuild-clang.sh
Make it use proper File list
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped
Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>
=> bug fix when using clang-format checker

ci/doc/maintenance.md
This commit is trivial. It is to update the existing maintenance document.
---
=> Maintenance: Updated maintainers of READEMD.md file

ci/taos/webhook.php
This commit is to update the existing message of the webhook handler
to help a debugging of webhook handler.
---
=> webhook: Updated webhook message for debugging

ci/taos/config/config-plugins-prebuild.sh
This commit is trivial. It is to fix typos.
---
=> config: Fixed typos

ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh
git repo of nnstreamer example changed, fix url.
=> [Apptest] fix repo url

ci/taos/plugins-base/pr-postbuild-build-android.sh
Set sdk path and build options, build Android lib using the script in nnstreamer.
=> [Android] API build script

ci/taos/plugins-base/pr-postbuild-build-android.sh
Use default build option in nnstreamer repo.
=> [Android] api build option

ci/taos/plugins-base/pr-postbuild-build-android.sh
=> [Android] fix ndk version

ci/taos/plugins-good/pr-prebuild-clang.sh
Do not audit old commits.
TODO: audit all new commits in PR
=> prebuild-clang/limit audit target to last commit

ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh
This commit is to update display message of the Doxygen module.
Let's minimize the display messages ASAP.
* Fixed incorrect variable
* Updated annotations
* Minimized display messages
=> [Module] Updated Doxygen facility

ci/taos/checker-pr-prebuild-async.sh, ci/taos/config/config-environment.sh
This commit is to omit display message ASAP of Pre-builder group.
Let's replace report structure with debug message structure.
---
=>  Update version and minimize report messages of pre-builder

ci/taos/plugins-good/pr-prebuild-cppcheck.sh
This ptach changes arguments of cppcheck.
`--std=posix` was deprecated.
=> [cppcheck] Change arguments of cppcheck

ci/taos/plugins-staging/pr-postbuild-bazel-ubuntu.sh
This commit is to add new module that is call Bazel-ubuntu module.
This module is to check both build test and run test with the
Bazel package on Ubuntu X86-64 distribution.
---
=> Module: Added the Bazel/Ubuntu checker

ci/taos/checker-pr-comment.sh, ci/taos/checker-pr-gateway.sh
This commit is to update the existing notice routine for new PR.
* Added a routine to handle selective audit function
* Updated a routine to comment to new PR
---
=> Updated PR notice routine

ci/taos/checker-pr-comment.sh, ci/taos/checker-pr-gateway.sh
This commit is to update the operation to comment a version
and notice information for new PR.
=> Updated a routine to comment a version info for new PR

ci/taos/plugins-staging/pr-postbuild-bazel-ubuntu.sh
This commit is to append time checke routine for bazel/android module.
---
=> Added time check for bazel/android module

ci/taos/checker-pr-comment.sh, ci/taos/checker-pr-postbuild-async.sh, ci/taos/checker-pr-prebuild-async.sh, ci/taos/config/config-environment.sh, ci/taos/plugins-base/pr-postbuild-build-android.sh, ci/taos/plugins-base/pr-postbuild-build-tizen.sh, ci/taos/plugins-base/pr-postbuild-build-ubuntu.sh, ci/taos/plugins-base/pr-postbuild-build-yocto.sh, ci/taos/plugins-good/pr-prebuild-clang.sh, ci/taos/plugins-good/pr-prebuild-coverity.sh, ci/taos/plugins-good/pr-prebuild-cppcheck.sh, ci/taos/plugins-good/pr-prebuild-doxygen-build.sh, ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh, ci/taos/plugins-good/pr-prebuild-executable.sh, ci/taos/plugins-good/pr-prebuild-file-size.sh, ci/taos/plugins-good/pr-prebuild-flawfinder.sh, ci/taos/plugins-good/pr-prebuild-hardcoded-path.sh, ci/taos/plugins-good/pr-prebuild-indent.sh, ci/taos/plugins-good/pr-prebuild-misspelling.sh, ci/taos/plugins-good/pr-prebuild-newline.sh, ci/taos/plugins-good/pr-prebuild-nobody.sh, ci/taos/plugins-good/pr-prebuild-prohibited-words.sh, ci/taos/plugins-good/pr-prebuild-pylint.sh, ci/taos/plugins-good/pr-prebuild-rpm-spec.sh, ci/taos/plugins-good/pr-prebuild-shellcheck.sh, ci/taos/plugins-good/pr-prebuild-sloccount.sh, ci/taos/plugins-good/pr-prebuild-timestamp.sh, ci/taos/plugins-staging/pr-postbuild-bazel-ubuntu.sh, ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh, ci/taos/plugins-staging/pr-postbuild-resource.sh
This commit is to update the repository name structure to handle
multiple projects per a one repository.
=> Upstream onerepo multiprjs

ci/taos/plugins-staging/pr-postbuild-bazel-ubuntu.sh
This commit is to add a code flow graph in the bazel module.
It is to be used to optimize code size of generated ELF file.
---
=> Added code flow graph in bazel module

ci/taos/plugins-staging/pr-postbuild-bazel-ubuntu.sh
This commit is to append a graph variable to improve portability.
---
=> Updated graph variables for code flow

ci/taos/checker-pr-postbuild-async.sh, ci/taos/config/config-environment.sh, ci/taos/plugins-staging/pr-postbuild-bazel-ubuntu.sh
* Enabled review activity
* Added Bazel debug option
=> Enabled review activity and Added Bazel debug option

ci/taos/checker-pr-postbuild-async.sh
This commit is a trivial. It is to fix incorrect 'echo' statements.
---
=> Fixed echo statements of post-build group

ci/taos/checker-pr-postbuild-async.sh
This commit is trivial. It is to fix an incorrect emoji grammar.
---
=> Fixed typo (incorrect emoji)

README.md
Happy new year. This commit is to change the existing branch name
from master to main.
Fixed #663
---
=> Changed the default branch (master to main)

README.md
This commit is to append an ICSE-SEIP paper "LightSys" in the README.md file. 
We got the acceptance notice from the ICSE program committee on Jan-06-2021.
---
=> Updated README.md for ICSE conference paper

ci/Doxyfile.prj
Let's allow the extraction of static function for more information.
=> [Doxygen] Extract static function

ci/taos/plugins-good/pr-prebuild-coverity.sh
Fix invalid URL to submit coverity build result.
=> [Coverity] Fix invalid url and code clean

CODE_OF_CONDUCT.md, README.md, ci/doc/coding-convention.md, ci/doc/contributing.md, ci/doc/doxygen-documentation.md, ci/doc/hotdoc/gen-hotdoc.sh, ci/doc/hotdoc/index.md, ci/doc/hotdoc/sitemap.txt, ci/doc/hotdoc/theme/extra/css/extra_frontend.css, ci/doc/hotdoc/theme/extra/templates/navbar_links.html, ci/doc/how-to-archive-large-data.md, ci/doc/how-to-build-gbs-pdebuild.md, ci/doc/how-to-good-commit-message.md, ci/doc/how-to-install-taos-ci.md, ci/doc/how-to-setup-taos-ci-server.md, ci/doc/how-to-unit-testing.md, ci/doc/how-to-use-lcov-to-generate-code-coverage-stat.md, ci/doc/how-to-use-taos-ci-module.md, ci/doc/maintenance.md, ci/doc/self-assessment-before-submitting-pr.md, index.md
Generate TAOS-CI docs.
See: https://taos-ci.github.io/
=> [Docs] Generates TAOS-CI docs

ci/taos/plugins-base/pr-postbuild-build-tizen.sh
This commit is to handle three gbs configuration files to compile source files
with the "gbs build" command.
For example,
First,  CUSTOM_GBS_CONF01="./.TAOS-CI/.gbs.conf"
Second, CUSTOM_GBS_CONF02="./packaging/.gbs.conf"
Third,  CUSTOM_GBS_CONF03="~/.gbs.conf"
---
=> [URGENT] Module: Added three gbs configuration files for Tizen build

ci/doc/how-to-install-taos-ci.md
Add a Trouble shooting to the how-to-install-taos-ci doc.
=> [Doc] Add trouble shooting

ci/taos/plugins-base/pr-postbuild-build-tizen.sh
This commit is to append a routine to calculate automatically user-id
and home-folder that are used by a default account of web-server
(e.g., Apache, Nginx).
---
=> [Module:Tizen] Added routine to get user-id and home-folder @open sesame 02/05 21:09

ci/badge/gen_badge.py
Change gen badge script for python3
Self evaluation:
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped
=> [Badge] Change gen badge script

ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh
- [Doxygen Tag] Add report for the plugin 
```
This patch enables to generate a report for the doxygen tag plugin
```
=> [Doxygen Tag] Add report for the plugin @open sesame 04/22 13:38

ci/taos/plugins-staging/pr-postbuild-build-ml-api-android.sh
Fix android build script.
This makes the script available on nnstreamer.
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
=> [Staging] Fix android build script

ci/taos/checker-pr-gateway.sh, ci/taos/checker-pr-postbuild-async.sh
- [gateway] Move approve to gateway 
```
This patch moves approve comment to gateway since approve should wait for
prebuild group to be successful as well
```
=> [gateway] Move approve to gateway @open sesame 04/22  13:37

ci/taos/plugins-staging/pr-postbuild-build-ml-api-android.sh
Change script path to build Android library.
We now prepare Java library on Ubuntu, see https://github.com/nnstreamer/api/pull/72 for this.
=> [Android/NNStreamer] change path to build script

ci/taos/config/config-plugins-postbuild.sh, ci/taos/plugins-staging/pr-postbuild-build-ml-api-ubuntu-java.sh
Add post build plugin - nnstreamer java API for ubuntu
See : [personal repo CI test result](http://nnstreamer.mooo.com/nnstreamer-api-gichan/ci/repo-workers/pr-checker/2-202106301726070.98615694046021-20d1241673cdb8532ef06b7c91e6113f631aa365/report/build_log_2_ubuntu_java_output.txt)
=> [Plugin] Add post build plugin - nnstreamer java API for ubuntu

ci/Doxyfile.prj
=> Added Doxygen options to enable caller graphs

ci/taos/checker-issue-comment.sh, ci/taos/checker-pr-comment.sh, ci/taos/checker-pr-gateway.sh, ci/taos/checker-pr-postbuild-async.sh, ci/taos/checker-pr-prebuild-async.sh, ci/taos/common/api_collection.sh, ci/taos/common/out-of-pr-killer.sh, ci/taos/common/pr-scheduler.sh, ci/taos/config/config-environment.sh, ci/taos/config/config-plugins-postbuild.sh, ci/taos/config/config-plugins-prebuild.sh, ci/taos/config/config-server-administrator.sh
This commit is to replace # with ## for enhancing doxygen generation operations.
=> Doxygen: Replaced # with ## for fully doxygen generation
