nnstreamer/TAOS-CI

ci/standalone/plugins-base/pr-audit-build-ubuntu.sh

This commit is to handle correctly the default enviromment variables
in case that envrionment is suddenly changed due to Yocto/Poky eSDK.
1. Added /etc/environment for ubuntu build
---
```bash
blank line separating the summary from …
```

[Ubuntu build] Reload existing setting when Yocto changes env setting - @open sesame 08/16 19:25

---

ci/standalone/checker-pr-format-async.sh
ci/standalone/config/config-plugins-format.sh
ci/standalone/plugins-good/pr-format-cppcheck.sh
ci/standalone/plugins-good/pr-format-executable.sh
ci/standalone/plugins-good/pr-format-file-size.sh
ci/standalone/plugins-good/pr-format-hardcoded-path.sh
ci/standalone/plugins-good/pr-format-nobody.sh
ci/standalone/plugins-good/pr-format-timestamp.sh

This commit is to rearrange modulable facilities from core module into
plugins-good folder.
(format, cppcheck, executable, hardcoded-path, nobody, and timestamp)
1. Modualized a format facility
2. Modualized a cppcheck facility
3. Modualized a executable facility
4. Modualized a hardcoded-path facility
5. Modualized a nobody facility
6. Modualized a timestamp facility
7. Added plugins-good modules into configuration file
- The modules are enabled by default.
---
```bash …
```

Separated modulable facilities from core module to plugins-good folder

---

ci/standalone/body.php

This commit is trivial. 
This commit is to fix an incorrect html tag in body.php
---
```bash
Further …
```

Fixed typo of body.php

---

ci/doc/how-to-install-taos-ci.md

It's trivial. This commit is to fix an incorrect link in TAOS-CI install document.
---
```bash
Further …
```

doc: fixed typo in TAOS-CI install document

---

ci/taos/checker-pr-audit-async.sh
ci/taos/plugins-base/pr-audit-build-tizen.sh
ci/taos/plugins-base/pr-audit-build-ubuntu.sh
ci/taos/plugins-base/pr-audit-build-yocto.sh

This commit is to reorganize a queue structure of the existing platform
package builder. The three job queues handle a job status of the commit requests
that are managed by the commit scheduler.
* Before: wait trigger and run trigger
* After : wait, ready, and run queue
1. Added web hook apis additioanlly
2. Updated annotations
3. Updated the existing queue structure
4. Renamed a build queue by appending postfix '-run-queue'
---
```bash
Summarize changes in around 50 characters …
```

[Audit] Reorganize queue structure of platform package builder

---

ci/taos/checker-pr-audit-async.sh
ci/taos/checker-pr-format-async.sh
ci/taos/config/config-plugins-audit.sh
ci/taos/config/config-plugins-format.sh

It's trivial. This commit is to update the existing annotations in configuration files.
It will be helpful to users that have to enable or disable the existing lots of modules.
---
```bash
various …
```

config: fixed typos in configuration files

---

ci/doc/how-to-use-taos-ci-module.md
ci/taos/checker-pr-audit-async.sh
ci/taos/checker-pr-format-async.sh

This commit is to save a debug message for debugging in case that
the grammar of module(s) is not correct while running all modules
(both format and audit modules).
1. Added log file to save a debug message in case of incorrect grammar of module.
2. Added documentation
**Case study:**
```bash
$ bash ./pr-format-{module-name}.sh 2> debug.txt ; cat ./debug.txt
line 68: syntax error near unexpected token `fi'
`            fi'
```
---
```bash
Summarize changes in around 50 …
```

module: added debug message to inspece grammar of module

---

ci/gcov/coverage_generator.sh
ci/taos/menu.html

Using this script, coverage files created at ci/gcov folder.
Fixes issue #126
Signed-off-by: sewon.oh sewon.oh@samsung.com

[Unittest] Make script to auto-generate coverage files.

---

ci/taos/config/config-plugins-format.sh
ci/taos/plugins-good/pr-format-doxygen-tag.sh
ci/taos/test/pr-report.sh

This commit is to rename the existing doxygen module for readability and maintenance.
* before: pr-format-doxygen
* after : pr-format-doxygen-tag
1. replace format-doxygen with format-doxygen-tag
---
```bash
blank line …
```

module: replaced format-doxygen with format-doxygen-tag

---

ci/taos/checker-pr-audit-async.sh
ci/taos/checker-pr-format-async.sh

It is a trivial commit. This commit is to append debug messages to monitor
the loding status of plugin modules.
---
```bash
if you run the …
```

[debug] Added debug message for plugin modules

---

packaging/taos-ci.spec

Fixes issue #235.
This commit is to append a taos-ci RPM package for RPM-based Linux distrubitons
such as Redhat, CentOS, and Tizen.
1. Added 'noarch' build architecture.
2. Added taos-ci.rpm
TAOS-CI, The Per-PR CI System for TAOS Packages.
AOS-CI is an automated project coordinator to accelerate software development
based on the GitHub webhook API. It is aimed at preventing unexpected regressions
and potential bugs due to incorrect PRs while maintaining a GitHub repository.
3. Updated unittest-coverage-assessment.rpm
It is a python script that executes functions of source code to test a code
coverage statistics using GCOV and LCOV. LCOV is a graphical front-end
for GCC's coverage testing tool gcov. It collects gcov data for multiple source
files and …

packaging: added taos-ci RPM package for Redhat/CentOS/Tizen

---

debian/changelog

When run "debuild -uc -us" command, we meet a warning mesage as follows.
debuild: warning:     debian/changelog(l5): badly formatted trailer line
This commit is to fix a typo in Ubuntu changelog. We have to use double
white space before weekday.
---
```bash …
```

Correct typo in Ubuntu changelog

---

debian/control
debian/copyright

This commit is to improve the existing debian/* file to fix unexpected
build issues when running pdebuild.
1. Added Build-Depends for pdebuild (issue #244)
2. Updated description (within 80 column) to fix lintian warning
3. Changed copyright file
https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#copyright
---
```bash
characters or so. In some …
```

packaging: updated debian/{control,copyright} for lintain & pdebuild

---

ci/taos/webapp/install-nnstreamer-packages.sh
ci/taos/webapp/install-packages.sh

This commit is to update the existing scripts in order to install required
packages in the server. After this PR, a 'mk-build-deps' command of the
scripts install automatically dependent packages (e.g., libgtest-dev
package is required by unit test.)
* Version 3:
1. Added 'yes' command for auto 'Enter' key while running add-apt-repository
2. Added dirname statement to find debian/control file anywhere
* Version 2:
1. Introduced mk-build-deps command to install dependent packages automatically
2. Indicated a goal: 1) for CI-server, 2) for CI-system for readability and maintenance
* Version 1:
1. Added libgtest-dev in script file.

[CI-Server] script: improve bash scripts to install required packages

---

ci/taos/plugins-base/pr-audit-build-ubuntu.sh

print gmt time befor and after pdebuild and add time option.
---
```bash
Further paragraphs come after blank …
```

Add time check while ubuntu build

---

ci/taos/plugins-good/pr-format-cppcheck.sh

This commit is to append annotations of possible severities and inspection options.
Note that by default Cppcheck only writes error messages if it is certain.
The possible severities (e.g., --enable=warning,unusedFunction) for messages are as following:
1. error  : used when bugs are found
2. warning: suggestions about defensive programming to prevent bugs
3. style  : stylistic issues related to code cleanup (unused functions, redundant code, constness, and such)
4. performance: Suggestions for making the code faster. These suggestions are only based on common knowledge.
5. portability: portability warnings. 64-bit portability. code might work different on different compilers. etc.
6. information: Informational messages about checking problems.
7. unusedFunction: enable unusedFunction …

cppcheck: append annotations and check options

---

ci/taos/webhook.php

This commmit is to improve the existing security policy to avoid an unexecpted
security accident. After this PR, we display just two characters from a 'Screct'
value of a json-formatted configuration file.
* before: mywebhookpassword
* after : my******
---
```bash
subject of the commit and the rest of the text as the body. …
```

webhook: improved secutiry policy

---

ci/taos/plugins-good/pr-format-cppcheck.sh

1. 'bug_line=`wc - l ../report/$cppcheck' result is '{line count} {file name}' so, fix that.
2. check_result="skip" is defined top of function. It is unnecessary that re-assign "skip" when check other type.

[Fix/cppcheck] Edit ignoring condition and overwriting result bug

---

ci/taos/config/config-environment.sh
ci/taos/plugins-good/pr-format-cppcheck.sh

Fixes issue #270.
This commit is to append a check level of CPPCheck facility to provide
developers optional levels. It is an appropriate time to support two levels
to CPPcheck facility to avoid a lot of engineering burdens due to a defect report of
SVACE (Commercial software quality tool) at a release time.
* How to change a check level of CPPCheck facility:
Please modify variables in the config-environment.sh file.
* Proposed levels
CPPCheck Level 0:  (default check is 'err'.)
CPPCheck Level 1:  --enable=warning,performance,unusedFunction
pr_doxygen_check_level=0
pr_doxygen_check_level=1
---
Please remove unused part of the template after writing …

module: add check level of CPPCheck facility

---

ci/taos/config/config-plugins-format.sh
ci/taos/plugins-good/pr-format-sloccount.sh

Fixes issue #259.
This commis is to append a set of tools for counting physical Source
Lines of Code (SLOC) in a large number of languages of a potentially
large set of programs.
It summarizes the SLOC results and presents various estimates (such as
effort and cost to develop).
1. Added SLOCCount module to estimate the development cost of a project.
2. sloccount statement in config file.
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.co

module: add SLOCCount checker to estimate development cost @open sesame 10/05 15:03

---

ci/doc/how-to-setup-taos-ci-server.md

This commit is to fix a typo in server setting document.
Signed-off-by: www-data <www-data@u1604.invain.mooo.com>
---
```bash
Further paragraphs come after …
```

Fix typo in server manual

---

ci/taos/plugins-good/pr-format-sloccount.sh

It is trivial. This commit is to fix incorrect indentation of the slocc module.
1. Fixed incorrect indentation
2. Removed incorrect white spaces.
---
```bash
various …
```

slocc: fixed indentation of slocc module

---

ci/taos/config/config-plugins-format.sh
ci/taos/config/prohibited_words.txt
ci/taos/plugins-good/pr-format-prohibited-words.sh

Fixed issue #287.
This commit is to proved a prohibited words module in order to
check if there are unnecessary words in the text files.
Version 5:
1. inspect all source code files at one go
Version 4:
1. Displayed a file name and line number to help debugging
Version 3:
1. Used grep only instead of wc command
2. Fixed incorrect variable name
3. Created a log file for debugging
Version 2:
1. Added a rule file, prohibited_words.txt
2. replaced 'echo' with 'echo -e' to handle special characters
Version 1:
1. Added new module, 'pr-format-prohibited_words'
2. Added statement to enable prhibited words module in configuration file

Module: Added prohibited words facility

---

ci/taos/config/prohibited_words.txt
ci/taos/plugins-good/pr-format-prohibited-words.sh

This commit is to fix an incorrect count calculation of prohibited words checker
when a soue code files of a commit includes specified prohibited words.
1. Fixed incorrect count result when use $(....) statement of bash
2. Updated a report mode (e.g., success, failure, skip, and unexpected error).
---
```bash
characters or so. In some contexts, the first …
```

Plugin: fixed count issue of prohibited words checker

---

ci/taos/plugins-good/pr-format-prohibited-words.sh

This commit is to fix a typo of log file name in the
prohibited words checker.
---
```bash …
```

Urgent: [module] prohibited-words: fixed typo of log file

---

ci/doc/how-to-use-taos-ci-module.md
ci/taos/checker-pr-audit-async.sh
ci/taos/checker-pr-format-async.sh
ci/taos/checker-pr-signed-off-by.sh
ci/taos/common/api_collection.sh
ci/taos/plugins-base/pr-audit-build-tizen.sh
ci/taos/plugins-base/pr-audit-build-ubuntu.sh
ci/taos/plugins-base/pr-audit-build-yocto.sh
ci/taos/plugins-good/pr-format-clang.sh
ci/taos/plugins-good/pr-format-cppcheck.sh
ci/taos/plugins-good/pr-format-doxygen-build.sh
ci/taos/plugins-good/pr-format-doxygen-tag.sh
ci/taos/plugins-good/pr-format-exclusive-vio.sh
ci/taos/plugins-good/pr-format-executable.sh
ci/taos/plugins-good/pr-format-file-size.sh
ci/taos/plugins-good/pr-format-hardcoded-path.sh
ci/taos/plugins-good/pr-format-indent.sh
ci/taos/plugins-good/pr-format-misspelling.sh
ci/taos/plugins-good/pr-format-newline.sh
ci/taos/plugins-good/pr-format-nobody.sh
ci/taos/plugins-good/pr-format-prohibited-words.sh
ci/taos/plugins-good/pr-format-pylint.sh
ci/taos/plugins-good/pr-format-rpm-spec.sh
ci/taos/plugins-good/pr-format-sloccount.sh
ci/taos/plugins-good/pr-format-timestamp.sh
ci/taos/plugins-staging/pr-audit-resource.sh
ci/taos/plugins-staging/pr-nnstreamer-ubuntu-apptest.sh

Fixes issue #289.
This commit is to rename the existing API name of the CI bot to improve a readability of the APIs.
* Before: cibot_pr_report()
* After : cibot_report()
1. Rename the existing webhook API
---

API: replaced cibot_pr_report with cibot_report

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

Fixed the issue 651 (https://github.com/nnsuite/nnstreamer/issues/651).
This commit is to fix a potential security issue of /dev/video* in NNStreamer
apptest module.
Note that the server administrator must add 'www-data' (webapp id) account to
'video' group to access /dev/video*. Do not use '777' permission  to avoid a
security vulnerability.
1. Improved access method of /dev/video* (device node file)
2. Added dependent commands
---
```bash
Summarize changes in around 50 …
```

module: fix security issue of /dev/video* in NNStreamer apptest

---

ci/taos/checker-pr-gateway.sh
ci/taos/webhook.php

This commit is to unify the two check handlers such as format and audit.
Finally, "git clone" commad will be executed just once.
Fixed issue #299.
---
```bash
various tools like `log`, `shortlog` and …
```

Webhook handler: Unified two checkers (format and audit) @open sesame 10/16 19:09

---

ci/taos/checker-pr-audit-async.sh
ci/taos/checker-pr-format-async.sh
ci/taos/checker-pr-gateway.sh

PR-gateway: run git command just once
This commit is to execute 'git clone' command just once when
contributor submits a PR. This commit is a final step to complete
the issue #299.
* Fixed issue #299.

PR-gateway: run git command just once

---

ci/gcov/coverage-generator.sh

If not, only use pre-order rpm file. so remove rpm file after making coverage
Fixed issue : https://github.com/nnsuite/nnstreamer/issues/689
Signed-off-by: Sewon Oh <sewon.oh@samsung.com>

[Fix] Remove rpm file for unit test coverage

---

README.md

This patch fixed a typo about reference paper.
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>

DOC: fix a typo in README.md

---

debian/changelog

This commit is to fix a not compatible version naming structure.
Note that we may use a simple version number to avoid possibility of 
an unexpected generation issue when 'debuild' and 'git-buildpackage' (gbp) 
convert  ./debian/* files to *.dsc file.
---

Debian: fixed a not compatible version number - @open sesame 10/26 11:27

---

ci/taos/webapp/install-packages.sh

It is trivial. While setting new ci server(aws), I find it.
---
```bash
Further paragraphs come after blank …
```

[typo] fix typo

---

ci/doc/how-to-setup-taos-ci-server.md

This commit is to update the existing instruction manual to give users
more easy setting guide when developers try to set-up a sever environment
to run CI server newly.
1. Updated the existing server setting guide
---

doc: updated instruction manual to set-up a CI server

---

ci/taos/webapp/install-packages.sh

This commit is to fix incorrect package name by replacing 'pdfunite' with
'poppler-utils' package.
1. Replaced pdfunite with poppler-utils
2. Added package names to run a code coverage (gcov/lcov)
3. Updated some satements for readability
---
```bash
subject of the commit and the rest of …
```

server: Fixed incorrect package name in install-packages.sh

---

ci/taos/checker-pr-audit-async.sh

This commit is to fix an incorrect operation of Out-of-PR(OOP) killer
after completing unification of the "git clone" opertion with pr-gateway.sh
1. Replaced pr-audit.sh with pr-gateway.sh
---

Scheduler: Fixed incorrect operation of Out-of-PR killer

---

ci/taos/config/config-plugins-format.sh

It is trivial. fix the typo.
---
```bash
**Changes proposed in …
```

[Typo] Fix typo in config-plugins-format

---

ci/taos/plugins-good/pr-format-nobody.sh

remove unused variable and unncessary lin.
---
```bash
**Changes …
```

[Fix] remove unused & unnecessary line

---

ci/taos/webapp/monitor.php

This commit is to fix the PR monitor of Ubuntu build.
1. Display the number of running ubuntu build tasks
---
```bash
various tools like `log`, `shortlog` and …
```

web: Improved how to display running Ubuntu build tasks

---

ci/taos/config/config-plugins-format.sh
ci/taos/plugins-good/pr-format-signed-off-by.sh

Check if a commit body has 'Signed-off-by' message.
resolves: #369 
---
```bash
various tools …
```

[module] implement signed-off-by plugin

---

ci/doc/how-to-setup-taos-ci-server.md

This commit is to fix an incorrect guide to set-up a base image of pbuilder.
Note that user can not access to /usr/sbin/ folder that 'pbuilder' is located
according to the security policy of Ubuntu distribution.
---
```bash
blank line separating the summary …
```

doc: update a cron manual for pbuilder

---

ci/taos/checker-pr-audit-async.sh
ci/taos/common/api_collection.sh
ci/taos/common/pr-scheduler.sh

This commit is to modularize the existing operation of the PR scheduler to handle
the build tasks between run-queue (enqueue) and wait-queue (dequeue).
* Version 2:
1. Removed duplicated statements
- check_running_jobs()
2. Added coopyright statement
* Version 1:
1. Added pr-scheduler.sh for modularization in the common folder.
2. Moved the PR scheduler to control the system resources (e.g, CPU, MEM, Storage)
- before: Run a controlling process to manage run-queue and wait-queue.
- after:  Run a controller process per every package builder
to avoid the PR hang situation
3. Added annotations.

PR Scheduler: modularize to control the server overhead 

---

ci/taos/plugins-good/pr-format-signed-off-by.sh

change name from 'signedoff' to 'signed-off-by'
---
```bash …
```

[Fix] change report name

---

ci/taos/plugins-base/pr-audit-build-tizen.sh

For unit test of nnstreamer, add flag.
---
```bash
**Changes …
```

[Tizen] When arch x86_64 gbs build, add unit test flag

---

ci/taos/plugins-base/pr-audit-build-tizen.sh

This blank make error that 'command not found'
---

[Fix] Remove blank at tizen build option.

---

ci/taos/checker-pr-audit-async.sh
ci/taos/common/out-of-pr-killer.sh

Fixed issue #412.
This commit is to modularize the existing Out-of-PR(OOP) killer.
Out-Of-PR(OOP) killer is to stop compulsorily the previous same PRs invoked by
checker-pr-gateway.sh when the developers try to send a lot of same PRs
repeatedly.
* Version 2:
1. Updated comments
* Version 1:
1. Modulairzed OOP killer for maintenance and re-usability

Common: Modularize out-of-pr killer

---

ci/taos/config/config-environment.sh
ci/taos/config/config-plugins-audit.sh
ci/taos/config/config-plugins-format.sh
ci/taos/config/config-server-administrator.sh

This commit is to remove the existing license statements in the configuration files.
It aims to give users convenience when a github repository (that use different license)
try to introduce TAOS-CI system.
---

Remove license statement in configuration files

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

---
Resolves the PR https://github.com/nnsuite/nnstreamer/pull/896
Since https://github.com/nnsuite/nnstreamer/pull/896 moves libtensor_filter_tflitecore.so to ${libdir} from ${gst_install_dir}, the audit for apptest on Ubuntu was failed. This PR resolves this issue.
* Version 3:
- The missing cmake argument, -DCMAKE_INSTALL_LIBDIR=lib, is added.
* Version 2:
- This PR is changed to include only related one patch
* Version 1:
- [nnstreamer/apptest] Revise cmake arguments

[nnstreamer/apptest] Fix apptest failure

---

ci/taos/checker-pr-audit-async.sh

Fixed issue #428.
This commit is to update the existing archive folder to keep generated package files.
1. Changed archive folder of .deb files from root folder to $BIN_FOLDER
2. Added a folder to archive generated packages files (.rpm and .deb)
3. Added two-step operation (a. copy pack files, b. remove unnecessary files)
4. Appended annotations for maintenance
5. Cleaned unnecessary files in the root folder of a PR (for readability)
---

[Build] Updated a removal operation and archive folder

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

* Related issue: https://github.com/nnsuite/nnstreamer/issues/905
It is to add help debug message additionally. This commit is to append
a debug message in order that the developer can monitor a current
environment setting content with 'env' command.
1. Added 'env' command to display meaningful log message additionally
---

nnstreamer/apptest: Added debug message to display  environment

---

ci/taos/plugins-base/pr-audit-build-ubuntu.sh

This commit is to change the existing folder name of the Ubuntu pakcages
as following:
* Before:
./binary_repository/RPMS/
./binary_repository/
* After:
./binary_repository/RPMS/ (for Tizen)
./binary_repository/DEBS/ (for Ubuntu)
---

build/ubuntu: Change ubuntu pack folder

---

ci/taos/common/global-variable.sh
ci/taos/plugins-base/pr-audit-build-yocto.sh
ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

* Related issue: https://github.com/nnsuite/nnstreamer/issues/905
- Fix broken message in the output file
(e.g., 쁬obilenet_v1_1.0_224_quant.tflite, 쁫abels.txt)
This commit is to declare a default locale policy for build modules.
From our experience, we need to use a locale setting which supports UTF-8
to avoid an unexpected locale issue while running audit modules.
* Case study:
1) Yocto: "devtool add/build" command is not executed because it is written by a UTF-8 library.
2) Download: A log message is broken while downloading a file with no locale setting
* Defaut policy:
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
---
2. Run test: [ …

Audit modules: Specify a default locale policy.

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

This commit is to change the default connection port of Xvnc from 6011(:11)
to 6031(:31) in order to guarantee always a port creation of the Xvnc server
because some utiltiies try to use port 603x as well as port 601x.
1. Added debug message (e.g., 59xx, 60xx port)
2. Replaced :11 with :31 for stability
3. Updated annotations
---

nnstreamer/apptest: Improved Xvnc connection

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

This commit is to kill the Xvnc service if (1)/dev/video0 file does not exist
and (2)port 6031 is still opened.
* How to get the port number:
xvnc_port=$(ps -A -o pid,cmd | grep "[\:]31" | awk '{printf $1}')
---

nnstreamer/apptest: kill Xvnc in case of !/dev/video0 and :31 port

---

ci/taos/common/global-variable.sh

This commit is to append a default environment variables to run commands
that is called by 'www-data' of Apache webserver.
1. Added SHELL and TERM variable
---

nnstreamer/apptest: specify a default env variables

---

ci/doc/how-to-setup-taos-ci-server.md

Fixed issue https://github.com/nnsuite/nnstreamer/issues/955.
This commit is to fix an incorrect lifespan management of out-of-date PR folders.
* before:
$ find /var/www/html/TAOS-CI/ci/repo-workers/ \
-maxdepth 2 -type d -mtime +6 -exec rm -rf {} \;
* after:
$ find /var/www/html/TAOS-CI/ci/repo-workers/pr-checker/* \
-maxdepth 2 -type d -mtime +6 -exec rm -rf {} \;
---

[Doc] Fixed a lifespan management of PR folders

---

ci/taos/plugins-good/pr-format-doxygen-tag.sh

This patch fixes a broken link to doxygen-documentation.md in the doxygen-tag module.

module: doxygen-tag: Fix broken link to doxygen-documentation

---

README.md

This patch fixes a broken link to the 'Build Status' page.

doc: Fix a broken link to the 'Build Status' page

---

ci/taos/config/config-environment.sh
ci/taos/config/config-plugins-audit.sh
ci/taos/plugins-base/pr-audit-build-android.sh

This commit is to support a Android build module to generate the .so files
from native C/C++ source code. In general, these .so files are used as a
low-level library for Android Application framework. Then, These files have
been enabled by Android application via JNI interface.
As a result, it is to be used as a native libraries on Android devices.
* Goal:
Support an Android build module (with ndk-build) to restrain the inconsistency
of C/C++ code compilation can be broken because of the incorrect PRs.
---

[v4] Audit group: Support a Android build module for C/C++

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

Before adding a script to build nnstreamer plugins, set env variables for nnstreamer.
TODO :
We have to build (or download) nnstreamer plugins later.

[nnstreamer/apptest] update env variables

---

.github/CODEOWNERS

This commit is to update the existing 'CODEOWNERS' file for
a code review process. After this PR, @kparichay will be
automatically included in the reviewer list.
---

CODEOWNERS: update auto review list

---

ci/taos/webapp/monitor.php

This commit is to support a monitor facility to display running PRs to
build C/C++ Android libraries with ndk-build command.
---

web: Added monitor to show running PRs to build Android binaries

---

ci/taos/plugins-good/pr-format-cppcheck.sh

Display the cppcheck version that is installed in the CI server.
Note that the out-of-date version can generate an incorrect result.
For example, cppcheck --version
---

cppcheck module: display the version information into log file

---

debian/changelog
packaging/taos-ci.spec

This commit is to synchronize the version info between packaging
files such as ./debian/changelog and ./packaging/taos-ci.spec file.
---

version management: sync version between packaging files

---

ci/jenkins/test-coverage-gcov.sh

This patch changes the repository address that is used for getting the latest nnstreamer-unittest-coverage rpm file. This change will make ci get the rpm file from the public address, http://download.tizen.org, where packages are released more frequently.

[Jenkins/Coverage] Use public repo for nnstreamer-unittest-coverage

---

ci/taos/plugins-base/pr-audit-build-android.sh
ci/taos/plugins-base/pr-audit-build-tizen.sh
ci/taos/plugins-base/pr-audit-build-ubuntu.sh
ci/taos/plugins-base/pr-audit-build-yocto.sh

Fixed issue #466.
The build time is always PITA when the PRs are suddenly submitted.
This commit is to support a build time recorder to display a required time
to complete a build procedure whenever contributors submit a PRs.
**Changelog**
1. Added variables to check start and end time.
2. Updated the webhook message to inform contributors of an estimated build time
3. Applied the function to Ubuntu, Tizen, Yocoto, and Android module.
---

plugin-base: Added a time checker to display a build time of PR

---

ci/taos/plugins-base/pr-audit-build-android.sh
ci/taos/plugins-base/pr-audit-build-tizen.sh
ci/taos/plugins-base/pr-audit-build-ubuntu.sh
ci/taos/plugins-base/pr-audit-build-yocto.sh

This commit is to change the output format of the existing build modules for readability.
After this PR, The build time information will be displayed on the screen.
* Before: 07 minutes and 24 seconds
* After : 07m 24s
---

Build: Changed the display format of build modules

---

packaging/.gbs.conf

This commit is to fix incorrect statement in .gbs.conf file.
If we write multiple repositories in varaible 'repos',
the last repo is finally overwritten.
---

Tizen: update the incorrect repo statement in .gbs.conf

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

To run app-test in nnstreamer repo, clone nnstreamer-examples and install the examples.
**Changelogs**
* Version 2:
- update the description
* Version 1:
- add script to build the nnstreamer examples

[nnstreamer/apptest] script to build examples

---

ci/Doxyfile

This commit is to replace the existing project name with
an appropriate project name as a default template.
Signed-off-by: junghan <junghan@skku.edu>
---

Doxygen: Fixed incorrect project name

---

ci/gcov/coverage-generator.sh

Fixed issue #https://github.com/nnsuite/nnstreamer/issues/1275.
This commit is to improve the exsiting coverage generator
to fix an unexpected situation that we sometimes have got a
code coverage report based on out-of-date version.
**Changelog**
1. Rewrote the operation flow of coverage generator
2. Keep the bash writing style with a standard grammar
to support a compatibility  between different bash versions
3. Added debug message to figure out a reason in case of an error
4. Improved gbs build command to avoid incorrect reference of a
repository cache folder.
---

Code Coverage: Improved the coverage generator

---

ci/gcov/coverage-generator.sh

This commit is to fix incorrect gcov filder.
---
```bash …
```

fixed incorrect gcov folder

---

packaging/taos-ci.spec

Tis commit is to add the coverage-generator.sh file into
the unittestcoverage.rpm file.
**Changelog**
1. Added coverage-generator.sh (based on cron daemon)
2. Updated indentations of tags
3. Removed out-of-date unittestcoverage.py (symbolic link).
- This file is maintained in ./tests/ folder of each repository.
---

Tizen: updated .spec file

---

ci/badge/gen_badge.py

This patch adds a python script for generating github badges of SVG file format. Note that only 'codecoverage' badge is supported for now.
- License is changed to Apache-2.0
- For the external python packages, comments indicating PyPi pages are added.

[Tool] Add a python script for generating github badges

---

ci/gcov/coverage-generator.sh

This patch adds a new procedure that generates a github badge for representing 'code coverage'.
- V2: Add an indentation
https://github.com/wooksong/nnstreamer-ros/tree/add-readme

[gcov] Add a procedure for generating a 'code coverage' badge

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

The 'wget' command saves a log message with the "-o logfile" option
while downloading files. This commit is to run a locale setting which
supports 'utf-8' to avoid an issue  that some file names in the log
file are broken.
* Reference: https://github.com/nnsuite/nnstreamer/issues/1280
---

NNstreamer-AppTest: Added a locale setting for wget command

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

The apptest module for nnstreamer, downloads a file from the specified
URL at first. Then, it archives the files /tmp folder. It means that
the download files are continually archived in /tmp folder until the
server will be rebooted.
This commit is to display exactly execution status of 'wget' command
between a download mode (first) and caching mode (from second).
**Changelog**
1. Replaced wget.log with wget_status.oog
2. Update debug messages
3. Separated the two statuses such as a download and caching mode.
---

NNstreamer/Apptest: Improve debug message to monitor wget status

---

ci/taos/checker-pr-gateway.sh
ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

This commit is to replace .log with .txt in order to improve compatibility
and readability when press the log files among the browsers. The www-data
of Apache web-server executes the scripts based on the configuration file
of Apache httpd daemon. In case of text files, let's use .txt format instead
of the .log file extension.
---

Changed a extension format of log files (.log to .txt)

---

ci/taos/checker-pr-format-async.sh

This commit is trivial. It is to synchronize the existing file extensions
consistently. Let's replace .log with .txt to read log files normally in
most of the web browsers.
**Changes*
1. Added comment
2. Replaced .log with .txt
---

format group: Replace .log with .txt

---

ci/taos/checker-pr-gateway.sh

Fixed issue https://github.com/nnsuite/nnstreamer/pull/1231
This commit is to return the exeuction method from asynchrnous (recently)
to synchronous method because the format group still not heavy.
Let's execute the checkers in order synchronously.
1. Run each checker in order: format checker and audit checker
2. Run policy between two methods
- Method1: If a checker is failed,
the check procedure will be stopped without starting a next checker.
- Method2: Although a checker is failed,
a next checker will be started continually.
---

Out-of-PR Killer runs based on synchronous technique

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

This commit is trivial. This commit is to improve a readability of the
log file that is generated by NNstreamer apptest module to evaluate
the GUI application in the Cloud (e.g., Amazone AWS EC2).
The test scenario to evaluate sample applications, is as following:
a. Start a producer
b. Start consumer(s)
- Connect the producer to open a session for virtual display environment.
- Run an application while 2 seconds arbitrarily
- Kill a process of the application after 2 seconds. Otherwise, the process runs forever.
c. Report the execution result with a webhook API.
---

nnstreamer/apptest: improve readability of log file

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

set valid conf file path for nnstreamer
**Changelogs**
* Version 2:
- remove unnecessary env variables to get sub-plugins
* Version 1:
- fix invalid conf path

[app-test] fix invalid conf file

---

ci/taos/webapp/install-packages-nnstreamer.sh

This commit is to append 'python-numpy' & 'python3-numpy' to installed packages

[nnstreamer/apptest] Added dependency: python-numpy & python3-numpy

---

ci/doc/how-to-good-commit-message.md

This commit is to describe how to write a changelog when a commit is updated.
**Keep a changelog**
A changelog is a file which contains a chronologically ordered list of notable
changes for each version of a commit. I has to be written to make it easier for
users and contributors in order to see precisely what notable changes have been
made between each version of the commit.
When a commit changes, reviewers want to know why and how.
---

doc: Added how to write a changelog 

---

ci/taos/plugins-staging/pr-audit-nnstreamer-ubuntu-apptest.sh

We not have scripts to download models for example apps.
And, the standard paths to models have been updated.
Apply such changes to avoid CI errors.
This fixes CI errors of nnstreamer. Testing in progress.

[Staging/NNStreamer-Apptest] Update tflite model download script

---

ci/taos/plugins-base/pr-audit-build-android.sh

Print the error log while building Android API library.

[Android] printout build log

---

ci/taos/config/config-plugins-format.sh
ci/taos/plugins-good/pr-format-flawfinder.sh
ci/taos/webapp/install-packages-base.sh

Fixed issue #522.
This module is to examines C/C++ source code and reports possible security weaknesses.
Flawfinder  searches  through C/C++ source code looking for potential security flaws. It examines
all of the project's C/C++ source code. It's very useful for quickly finding and removing some
security problems before a program is widely released.
Flawfinder produces a list of ``hits'' (potential security flaws), sorted by risk; the riskiest
hits are shown first.  The risk level is shown inside square brackets and  varies  from  0,
very little risk, to 5, great risk.  This risk level depends not only on the function,
but on the values of the parameters of the function.  For example, constant strings are often less risky
than fully variable strings in many contexts, and in those …

module: Added flawfinder checker for finding security flaws

---

ci/taos/common/api_collection.sh

This commit is to display the hint message when the administrator
of CI server does not install the required packages.
---

Added webhook API to display a cmd dependency

---

ci/taos/plugins-base/pr-postbuild-build-android.sh

Related to https://github.com/nnsuite/nnstreamer/pull/1827
See also https://github.com/nnsuite/nnstreamer/pull/1824#issuecomment-545848382
According to the recent modification in the build script for NNS Android API Library, this patch removes the step for patching C-API header to use it on non-Tizen platform.

[Base/Build/Android] Remove the step for patching Non-Tizen

---

ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh

Although it is a multi-line comment, do not make errors
for boilerplates even if it starts with /*.
Assume that comments starting at line 1 is a boilerplate.
This is for
https://github.com/nnsuite/nnstreamer/pull/1841
, which is required by Tizen API/SDK post-processing.

[Doxygen-Tag] Boilerplate may start with /*

---

ci/taos/plugins-good/pr-prebuild-coverity.sh

This commit is to change the default execution frequency of the Coverity Scan service.
* Before: 23 hours
* After : 12 hours
---

coverity: changed default execution frequency

---

ci/taos/config/config-environment.sh

This commit is to delete the deprecated variables that are used
for enabling the coverity module. And it is to append yellow and
red card instead of warning card for managing github repository
with a fine-grained approach.
**Changelog**
* Added yellow and red card
* Removed deprecated variables
* Added annotation for config variables
---
```bash
characters or so. In some contexts, the first …
```

config: Removed deprecated variables for coverity module

---

ci/taos/webapp/pr-handler-proceed.php
ci/taos/webapp/pr-handler-runner.sh
ci/taos/webapp/pr-handler.php

Fixed issue #557
This commit is to append web-based PR handler in order that
the reviewers directly pass the execution result of the CI modules
that are generated due to pre-mature functions and unexpected
exception cases.
**Changelog**
* Added a PR template
* Added input data to change the PR status
* Added skeleton of a facility to handling the specified PR
---

webapp: Added PR handler to handle incorrect report of CI module

---

ci/taos/config/config-plugins-prebuild.sh

This commit is to disable the coverity module by default because
the coverity module requrres 2 conditions as follows to execute
the coverity module.
* Conditions:
* C1: Administrator must install the Coverity Scan packages.
* C2: Administrator must set-up a token key in configuration file.
---

config: disabled coverity module by default

---

ci/taos/plugins-good/pr-prebuild-coverity.sh

Incorrect Behavior (before this patch)
Num_Err == 0 ==> success
Num-Err <= Yellow ==> Yellow Card
Num-Err > Red ==> Red Card
Num-Err > Yellow && Num-Err <= Red ==> FAILURE
Correct Behavior (after this patch)
Num_Err == 0 ==> success
Num-Err <= Yellow ==> Green Card
Num-Err > Red ==> Red Card
Num-Err > Yellow && Num-Err <= Red ==> Yellow Card

[Coverity/Fix] Coverity check fails if it's too good. @open sesame 11/20 16:30

---

ci/taos/plugins-good/pr-prebuild-coverity.sh

This commit is to fix the incorrect handling while checking
the changed files.
**Changelog**
* Fixed the incorrect location of the variables
(from local to global)
* Fixed the incorrect variable name
---

[URGENT] coverity: fixed the incorrect handling for doc files

---

ci/taos/config/config-environment.sh
ci/taos/plugins-base/pr-postbuild-build-tizen.sh

Fixed issue #590.
Tizen: If each git repository must be defined by a different profile (e.g., ~/.gbs.conf),
The name of TIZEN_GBS_PROFILE can be given without the "profile." prefix as follows.
For example, [profile.tizen40_mobile] has to be declared with TIZEN_GBS_PROFILE="tizen40_mobile".
TIZEN_GBS_PROFILE=""
---

Tizen: Supported manual profile to handle lots of repos

---

ci/taos/webhook.php

This commit is to fix incorrect usage of the regular expression
when the wehook handler (PHP) check "@open sesame" tag.
* Input (PR title): a model is updatable - @open sesame 12/03 16:47
* Before this PR: "@open sesame 12/03 16:4"
* After  this PR: "@open sesame 12/03 16:47"
---

Fixed incorrect matching expression for webhook

---

ci/taos/webhook.php

This commit is to append commit number and action state to the
existing webhook interface. It is to handle 1PR-ManyCommits and
Repeated comment issue.
---

webhook: Added commit number and action state to webhook interface

---

ci/taos/plugins-good/pr-prebuild-coverity.sh

The logic error made all non-redcard PRs get redcards.
Fixes #599

Coverity: fix redcard/yellocard comments

---

ci/taos/menu.html
ci/unittest_result/README.txt

This commit is to append the archive folder of the unit-test.
The unit-test could be executed by Tizen GBS and Google Gtest.
---

webapp: Added unit-test result folder

---

ci/taos/checker-pr-postbuild-async.sh
ci/taos/checker-pr-prebuild-async.sh
ci/taos/plugins-base/pr-postbuild-build-android.sh
ci/taos/plugins-base/pr-postbuild-build-tizen.sh
ci/taos/plugins-base/pr-postbuild-build-ubuntu.sh
ci/taos/plugins-base/pr-postbuild-build-yocto.sh

This commit is to change the existing group name from "pr-{pre/post}-all"
to "pr-{pre/post}-group" to improve readability and clarify the meaning of
group name (e.g., prebuild group and postbuild group).
---

Maintenance: Change name of two groups for readability

---

ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh

To run tf-lite model in apptest, it is necessary to enable tensorflow-lite.

[Apptest] enable tf-lite

---

ci/badge/.htaccess

Add .htaccess to prevent image cache Since GitHub caches image files, badge is not updated on the fly. 

[Badge] Add .htaccess to prevent image cache @open sesame 05/28 20:24

---

ci/taos/plugins-good/pr-prebuild-clang.sh

Check C++ files only if "cxx-only" option is given
so that clang-format won't process C files.
https://github.com/nnstreamer/nnstreamer/pull/2437 requires this.
https://github.com/nnstreamer/nnstreamer/issues/2044 is related.
Changes in v2:
- May accept multiple arguments.
- Use "clang_option" instead of "option".

Enable C++-Only mode for clang module

---

ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh

For app-test, set ld_lib_path (nnstreamer install dir) and pkg_config.

[app-test] set nnstreamer lib and pkgconfig path

---

ci/taos/plugins-good/pr-prebuild-clang.sh

This patch fixes `pr-prebuild-clang.sh` to check `*.cc` and `*.hh`.
Currently, TAOS-CI haven't checked the clang format of nnstreamer
due to missing extensions.
CC: @myungjoo @leemgs 

[Clang] Fix pr-prebuild-clang.sh to check '*.cc' and '*.hh'

---

ci/taos/plugins-good/pr-prebuild-clang.sh

In older toolchains of Ubuntu, changing code style
generated build errors (order of headers relative to gstcheck.h)
Reset clang-format results before running other CI modules.

Fix/CI Build Error

---

ci/taos/plugins-good/pr-prebuild-doxygen-build.sh
ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh

This patch adds missing extensions for cpp source codes
in doxygen pre-build checking.

[Doxygen] Add missing extensions for cpp source codes

---

ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh

This patch removes pr-aduit-group.txt that doesn't exist anymore. The file link is replaced by the folder link.
In other words, `s/\/pr-aduit-group.txt//g`.
Discussion: #637
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nnstreamer/taos-ci/638)

Remove pr-aduit-group.txt in bot messages. Fixes #637

---

ci/taos/plugins-good/pr-prebuild-shellcheck.sh

This patch makes cibot do not make any comments on success,
but instead, it now appends an extra log on failure.

[Shellcheck] Don't make unncessary comments on success

---

ci/taos/plugins-base/pr-postbuild-build-tizen.sh

This commit is to append an annotation to describe how to fix the "gbs build" failure due to a broken QEMU ARM.
If the QEMU facility of "gbs build" command is broken, please run "reboot" command,
Or run the below statements to avoid the "reboot" procedure. 
https://wiki.tizen.org/OSDev/qemu-accel
$ echo -1 | sudo tee /proc/sys/fs/binfmt_misc/qemu-arm
---

Added  how to fix  the "gbs build" failure

---

ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh

This patch fixes a wrong message from failure of doxygen tag checking.

[Fix/Doxygen] Fix a wrong message from failure of doxygen tag checking

---

ci/taos/checker-pr-gateway.sh
ci/taos/config/config-environment.sh

Fixed issue #646.
This commit is to support a selective PR handler. It is to handle
a situation that developers want to maintain a GitHub repository
that includes multiple projects.
**Changelog**
* Updated configuration file
* Added a routine that examines if a PR include a specified folder
* Added a log file to maintain  the gateway facility of TAOS-CI
* Updated annotations
* Added debug messages
---

[Feature] Added selective PR audit @open sesame 10/12 19:44

---

ci/taos/checker-pr-gateway.sh
ci/taos/config/config-environment.sh

This patch fixes the curl command to parse the target directory.
It uses github api to get the list of modified files.

[Fix] fix the curl command to parse the target directory

---

ci/badge/gen_badge.py

This is a trivial patch to fix a typo in the heading comments.
2. Run test: [ ]Passed [ ]Failed [*]Skipped

GenBadge/typo: Fix a typo in the heading comments

---

ci/taos/plugins-base/pr-postbuild-build-tizen.sh

When the BUILD_MODE is set to 1, a command pipeline is used for running 'gbs build' and capturing the standard output of it using 'tee', which could return '0' even if the former 'gbs build' command fails. To fix this bug, this patch replaces the pipe, '|', between 'gbs build' and 'tee' with the redirections and removes 'tee'.
See also: 
- Before applying the PR, you can see https://github.com/nnstreamer/nnstreamer-ros/pull/42 and https://github.com/nnstreamer/nnstreamer-ros/pull/44 passed the build checkers even if the tizen build is failed.
- After applying the PR, https://github.com/nnstreamer/nnstreamer-ros/pull/43 could not pass the build checker.  
2. Run test: …

post-build-tizen/bugfix: Remove 'tee' connected to 'gbs build' via '|'

---

ci/doxybook/book-doxygen-publish.sh

Fixed issue #672.
This commit is to fix an incorrect operation of LibreOffice while running
the generate_cover() function. It seems that a version of LibreOffice
requires the 'sudo' permission in order to convert *.txt to *.pdf file.

Added error handling for generate_cover function

---

ci/taos/plugins-good/pr-prebuild-executable.sh

This patch initialize result variables. Without this patch,
each test might be affected the results of previous tests.
Related PR: https://github.com/nnstreamer/nnstreamer/pull/2906

[FIX] Initialize result variables

---

ci/taos/config/config-plugins-postbuild.sh

This commit is to add the configuration statements to support
the Bazel-Ubuntu checker. This feature will be disabled by default
as an optional feature.
---

[Config] Updated config file for bazel-android module

---

ci/taos/checker-pr-gateway.sh

When one repository has multiple projects, the configuraiton files
of the CI sever has to be carefully described.
This commit is to display a hint message when a administrator of CI
server set-up configuration setting (e.g., /var/www/html/.....).
---

Add log message in PR gateway

---

ci/taos/common/api_collection.sh

Fixed issue https://github.com/nnstreamer/TAOS-CI/issues/684
This commit is to add an API to do a review result on a pull request with curl
The API consists of five arguments as folows.
* arg1: Token number
* arg2: Event (e.g., APPROVE, REQUEST_CHANGES, or COMMENT)
* arg3: Description
* arg4: Commit ID
* arg5: API address
Note that you can use this API such as the below statement.
```bash
message="All CI checkers are successfully passed. LGTM."
cibot_review $TOKEN "APPROVE" "$message" "$input_commit"
"$GITHUB_WEBHOOK_API/$GITHUB_ACCOUNT/${PRJ_REPO_UPSTREAM_SERVER}/pulls/$input_pr/reviews
```
---

Added cibot_review() API newly

---

ci/taos/checker-pr-postbuild-async.sh

This commit is to enable a routine to execute a review approval process
when all CI modules are successfully passed.
---

Enabled a routine to execute review approval

---

ci/taos/common/api_collection.sh

This commit is to add GitHub webhook API address to maintain
the public APIs of TAOS-CI.

Added github webhook site

---

ci/taos/common/out-of-pr-killer.sh
ci/taos/common/pr-scheduler.sh
ci/taos/plugins-base/pr-postbuild-build-tizen.sh
ci/taos/plugins-base/pr-postbuild-build-yocto.sh
ci/taos/webapp/monitor.php

This commit is to support a custom gbs conf file.
If the ./packaging/.gbs.conf file exists, the gbs build uses this file.
If the ./packaging/.gbs.conf file does not exist, the gbs build uses
~/.gbs.conf file.
---

Tizen: Supported a custom gbs conf file

---

ci/taos/config/config-plugins-postbuild.sh
ci/taos/config/kas-files/README.md
ci/taos/config/kas-files/kas-YOUR-PROJECT-sample.yml
ci/taos/config/kas-files/kas-local-config.yml
ci/taos/config/kas-files/kas-poky.yml
ci/taos/plugins-staging/pr-postbuild-build-yocto-kas.sh

- Add postbuild plugin for yocto image build
- This plugin utilize python module "kas" to build yocto image
- This plugin can be used for build check custom yocto layer
- Add guide yml config files for kas build
REF:
- kas: github.com/siemens/kas
Please check:
https://github.sec.samsung.net/yongjoo1-ahn/meta-neural-network-yongjoo/pull/7
https://github.sec.samsung.net/yongjoo1-ahn/meta-neural-network-yongjoo/pull/6
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
Run test: [X]Passed [ ]Failed [ ]Skipped

[Plugin] Add plugin for yocto-kas build

---

ci/taos/plugins-base/pr-postbuild-build-tizen.sh

This commit is to replace "~" with "$HOME" to find the home
folder of the "www-data" account correctly.
---

Module: Fixed incorrect home folder (Tizen build)

---

ci/taos/plugins-base/pr-postbuild-build-tizen.sh

If there are no custom gbs config files, just run with default gbs conf
file.
Don't check existence of the default file.
#related issue : #695 

Module: Fix default gbs conf path

---

ci/taos/config/config-plugins-postbuild.sh
ci/taos/plugins-base/pr-postbuild-build-android.sh
ci/taos/plugins-staging/pr-postbuild-build-ml-api-android.sh

- Add postbuild plugin `build-ml-api-android` for ML API android build
- This plugin is for github.com/nnstreamer/api
- REF: #711
See example in https://github.com/anyj0527/api/pull/2
This resolves #711
1. Build test: [X]Passed [ ]Failed [ ]Skipped

[Plugin] Add plugin `postbuild-build-ml-api-android` 

---

ci/taos/checker-pr-prebuild-async.sh
ci/taos/plugins-good/pr-prebuild-clang.sh
ci/taos/webapp/install-packages-base.sh

Change clang format version from 4.0 to 6.0
ubuntu focal don't provide clang-format-4.0 as default.

[Clang Format] Change clang-format version

---

ci/taos/config/config-environment.sh
ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh

- [Doxygen] Add option to skip definition tag 
```
For doxygen, there is a requirement from nntrainer repository that
doxygen function definition should not be checked if the function
definition is inside a source.
This patch implments for the requirement as an option.
`pr_doxygen_check_skip_function_definition` if this flag is turned on,
doxygen checker does not check definitions inside a sourcefile(eg,
*.cpp)
Feature:
- Add option to skip definition for non header file
Additional Fix:
- Fix a doxygen checker to check the function declaration(prototype)
**How test was done**
- Apply to nntrainer repository.
- Check doxygen book is not uglyfied due to this change.
1. Build test: [X]Passed [ ]Failed [ ]Skipped
Signed-off-by: …
```

[Doxygen] Add option to skip definition tag @open sesame 04/21 19:30

---

ci/taos/config/config-environment.sh
ci/taos/plugins-base/pr-postbuild-build-android.sh

- [Android] Add option to set ndk-build path 
```
This patch enables setting `ndk-build` path rather than hardcoded path
1. Build test: [X]Passed [ ]Failed [ ]Skipped
```

[Android] Add option to set ndk-build path

---

ci/taos/config/config-environment.sh
ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh

- [Doxygen] Add option for default check flag 
```
This patch add flag to function doxygen checker
1. Build test: [X]Passed [ ]Failed [ ]Skipped
```

[Doxygen] Add option for default check flag

---

ci/taos/plugins-good/pr-prebuild-clang.sh

This patch fixes the extension check routine for pr-prebuild-clang.
Previously, it hasn't detected files correctly. For example,
`.clang-format` can be also detected, which should have been ignored.
1. Build test: [*]Passed [ ]Failed [*]Skipped
2. Run test: [*]Passed [ ]Failed [* ]Skipped

[Clang] Fix the extension check routine @open sesame 04/22 14:36

---

ci/taos/plugins-base/pr-postbuild-build-android.sh

This patch makes the android build cheker skip the dependency check
when its build mode is 99 (skip).

[Android] Skip the dependency check if build mode is 99 @open sesame 04/22 14:30

---

ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh

- [Doxygen] Allow copydoc tag instead of brief
```
Doxygen has `@copydoc` which would copy the documentation. When
documentation is copied, there is no need to contain `@brief` tag.
This patch allows having `copydoc` is ok instead of `brief`.
```
Cc: Parichay Kapoor <pk.kapoor@samsung.com>

[Doxygen] Allow copydoc tag instead of brief

---

ci/taos/plugins-staging/pr-postbuild-bazel-ubuntu.sh

Add a report for bazel build.
Currently, the log is included in `pr-postbuild-group.txt`

[Plugin] Add report for bazel build

---

ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh

It is difficult to find error when failed to build nnstreamer and example in ci.
Add build log into output report, so developer can check the build error while running the apptest.

[NNStreamer/Apptest] meson build log

---

LICENSE
ci/taos/checker-issue-comment.sh
ci/taos/checker-pr-comment.sh
ci/taos/checker-pr-gateway.sh
ci/taos/checker-pr-postbuild-async.sh
ci/taos/checker-pr-prebuild-async.sh
ci/taos/common/api_collection.sh
ci/taos/common/out-of-pr-killer.sh
ci/taos/common/pr-scheduler.sh
ci/taos/plugins-base/pr-postbuild-build-android.sh
ci/taos/webhook.php

This commit is to add a SPDX-License statement.
* APACHE-2.0-only
* https://spdx.org/licenses/
* SPDX Guide:
To use this license in source code, put one of the following SPDX
tag/value pairs into a comment according to the placement
guidelines in the licensing rules documentation.
Acked-by: Gichan Jang <gichan2.jang@samsung.com>

Added SPDX-License

---

LICENSE
ci/taos/checker-issue-comment.sh
ci/taos/checker-pr-comment.sh
ci/taos/checker-pr-gateway.sh
ci/taos/checker-pr-postbuild-async.sh
ci/taos/checker-pr-prebuild-async.sh
ci/taos/common/api_collection.sh
ci/taos/common/out-of-pr-killer.sh
ci/taos/common/pr-scheduler.sh
ci/taos/plugins-base/pr-postbuild-build-android.sh
ci/taos/webhook.php

APACHE-2.0-only --> Apache-2.0
Refer to "Finding #9" of https://lfscanning.org/reports/lfai/nnstreamer-2022-07-02-8eb54f0b-f36e-43ff-826f-80e9f251e17e.html

Fix inappropriate SPDX license tags

---

ci/taos/plugins-good/pr-prebuild-doxygen-tag.sh

nnstreamer's tensor-transform has a CI error.
This patch updates doxygen tag pattern written in upper case.
See also #736 
Signed-off-by: Yelin Jeong <yelini.jeong@samsung.com>

[doxygen] update doxygen tag pattern

---

ci/taos/plugins-staging/pr-postbuild-build-ml-api-android.sh

- Clone nnstreamer-edge and set proper env var.
- https://github.com/nnstreamer/api/pull/222 requires this PR to be merged.
Check https://github.com/anyj0527/api/pull/4
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
1. Build test: [ ]Passed [ ]Failed [X]Skipped

[plugin] Fix ml-api-android to build with nnstreamer-edge

---

ci/taos/plugins-staging/pr-postbuild-build-ml-api-android.sh

- Add missing env variable NNSTREAMER_EDGE_ROOT in ml-api-android build
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
1. Build test: [ ]Passed [ ]Failed [X]Skipped

[plugin] Add missing env variable in ml-api-android build

---

ci/taos/config/config-environment.sh
ci/taos/plugins-good/pr-prebuild-clang.sh

- Change clang format version by config file.
- Default version: 12

[clang-format] Change clang format version

---

ci/taos/plugins-good/pr-prebuild-pylint.sh

This patch adds condition to cibot comments only when there is a bug.
This PR prevents TAOS-CI makes comment like [this](https://github.com/nnstreamer/nnstreamer/pull/4233#issuecomment-1705023126)

[pylint] comment only when there is a bug

---

ci/taos/checker-pr-gateway.sh
ci/taos/checker-pr-postbuild-async.sh
ci/taos/checker-pr-prebuild-async.sh
ci/taos/webhook.php

- Get the name of base branch from the github PR and let plugins may use it.

[common] Add base branch name info
